const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={campaigns:[],contacts:[],companies:[],settings:{}},caps={},campaignId='',selected='',view='people',busy=false,session='';
function hasUnsavedDraft(){const p=state.contacts.find(p=>p.id===selected);return !!(p&&$('body')&&['body','subject','notes','stage'].some(k=>$(k).value!==(p[k]||'')));}
function leaveDraft(){return !hasUnsavedDraft()||confirm('Discard your unsaved draft and notes?');}
window.addEventListener('beforeunload',e=>{if(hasUnsavedDraft()){e.preventDefault();e.returnValue='';}});
function notice(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);}
function token(){return localStorage.getItem('maya_admin_tok')||'';}
async function api(path='',body){const auth=token();if(!auth)throw Error('Sign in to Maya Admin first.');const r=await fetch('/api/admin/outbound'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+auth,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(token()!==auth)throw Error('Your account changed. Reload this page.');const j=await r.json();if(!r.ok){if([401,403].includes(r.status)){$('signin').hidden=false;state={campaigns:[],contacts:[],companies:[],settings:{}};render();}throw Error(j.error||'Request failed.');}return j;}
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.message,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function load(){try{const j=await api();state=j.state;caps=j.capabilities;session=token();$('signin').hidden=true;if(!state.campaigns.some(c=>c.id===campaignId))campaignId=state.campaigns[0]?.id||'';render();notice('Workspace ready. Changes save to your account.');}catch(e){$('signin').hidden=false;notice(e.message,true);}}
const campaign=()=>state.campaigns.find(c=>c.id===campaignId);
const contacts=()=>state.contacts.filter(c=>c.campaignId===campaignId);
async function save(body){if(body.type!=='contact'&&!leaveDraft())throw Error('Save your draft before continuing.');const j=await api('/save',body);state=j.state;render();notice('Saved.');return j;}
function modal(title,html,submit,label='Save'){$('modal-title').textContent=title;$('modal-body').innerHTML=html;$('modal-submit').textContent=label;$('modal-form').onsubmit=e=>{e.preventDefault();run(async()=>{await submit(new FormData(e.target));$('modal').close();});};$('modal').showModal();}
function field(name,label,value='',type='input'){return `<label for="field-${name}">${esc(label)}</label>${type==='textarea'?`<textarea id="field-${name}" name="${name}">${esc(value)}</textarea>`:`<input id="field-${name}" name="${name}" value="${esc(value)}">`}`;}
function editCampaign(existing){modal(existing?'Edit campaign':'New campaign',field('name','Campaign name',existing?.name)+field('audience','Who do you want to reach?',existing?.audience,'textarea')+field('objective','Offer and objective',existing?.objective,'textarea')+field('competitors','Competitor names or domains (research notes)',existing?.competitors,'textarea')+`<label>Status</label><select name="status"><option value="active">Active</option><option value="paused" ${existing?.status==='paused'?'selected':''}>Paused</option></select>`,async data=>{const j=await save({type:'campaign',id:existing?.id,...Object.fromEntries(data)});if(!existing)campaignId=j.state.campaigns.at(-1).id;render();});}
function render(){
 const c=campaign(),people=contacts(),count=stage=>people.filter(p=>p.stage===stage).length;
 $('campaigns').innerHTML=state.campaigns.map(c=>`<button class="campaign ${c.id===campaignId?'active':''}" data-campaign="${esc(c.id)}">${esc(c.name)}<small>${state.contacts.filter(p=>p.campaignId===c.id).length} prospects · ${esc(c.status)}</small></button>`).join('')||'<p class="muted small" style="margin-top:18px">Start with a campaign for your ideal customers.</p>';
 document.querySelectorAll('[data-campaign]').forEach(b=>b.onclick=()=>{if(!leaveDraft())return;campaignId=b.dataset.campaign;selected='';render();});
 $('competitors').textContent=c?.competitors||'No competitor notes yet.';$('campaign-title').textContent=c?.name||'Your next conversation starts here.';
 $('providers').textContent=`Hunter: ${caps.hunter?'configured':'needs connection'}\nGoogle Sheets: ${state.settings.sheetId?'selected':'choose a sheet'}\nMaya: ${caps.ai?'configured':'needs connection'}`;$('providers').style.whiteSpace='pre-line';
 $('steps').innerHTML=['Define audience','Find companies','Find people','Verify','Draft','Review & reach out'].map((s,i)=>`<span class="step ${[!!c,state.companies.some(x=>x.campaignId===campaignId),!!people.length,people.some(p=>p.verification==='valid'),people.some(p=>p.body),people.some(p=>p.stage==='contacted')][i]?'done':''}"><b>${i+1}</b>${s}</span>`).join('<span class="muted">·</span>');
 $('stats').innerHTML=[['Prospects',people.length],['Verified',people.filter(p=>p.verification==='valid').length],['Contacted',people.filter(p=>['contacted','replied','meeting','closed'].includes(p.stage)).length],['Meetings',count('meeting')],['Closed',count('closed')]].map(([label,n])=>`<div class="stat"><strong>${n}</strong><span>${label}</span></div>`).join('');
 document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-selected',String(b.dataset.view===view));});
 if(!c){$('content').innerHTML='<div class="empty"><h2>A thoughtful introduction goes further.</h2>Create a campaign, import your sheet, or discover companies with Hunter.<br>Only real imported or discovered records appear here.</div>';return;}
 if(view==='results'){renderResults();return;}
 if(view==='companies'){renderCompanies();return;}
 const query=$('search').value.toLowerCase();const list=people.filter(p=>[p.name,p.company,p.email].join(' ').toLowerCase().includes(query)&&(view!=='emails'||p.email||p.body));
 if(!list.some(p=>p.id===selected))selected=list[0]?.id||'';
 $('content').innerHTML=`<div class="workspace"><div><div class="row spread" style="margin-bottom:12px"><span class="muted small">${list.length} prospects</span><button id="add-person">+ Add person</button><button id="export">Export CSV</button></div><div class="list">${list.map(p=>`<button class="person ${p.id===selected?'active':''}" data-person="${esc(p.id)}"><div class="row"><span class="avatar">${esc((p.name||p.company||'?').slice(0,2).toUpperCase())}</span><div><h3>${esc(p.name||p.company)}</h3><div class="muted small">${esc(p.title||p.company||p.domain)}</div></div></div><span class="badge">${esc(p.source)}</span><span class="badge ${p.verification==='valid'?'valid':''}">${esc(p.verification)}</span><span class="badge">${esc(p.stage)}</span><p class="small muted" style="margin-top:9px">${esc(p.email||'Email not found yet')}</p></button>`).join('')||'<div class="empty">Import prospects or add a person to begin.</div>'}</div></div><div id="detail"></div></div>`;
 document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{if(!leaveDraft())return;selected=b.dataset.person;render();});$('add-person').onclick=addPerson;$('export').onclick=exportCSV;renderDetail();
}
function renderDetail(){const p=state.contacts.find(p=>p.id===selected);if(!p){$('detail').innerHTML='<div class="empty">Select a prospect to see their details and email draft.</div>';return;}
 const blocked=p.stage==='suppressed';$('detail').innerHTML=`<section class="detail"><div class="row spread"><div><h2>${esc(p.name||p.company)}</h2><p class="muted">${esc(p.company)} · ${esc(p.title)}</p></div><span class="avatar">✦</span></div><div class="actions"><button id="find-email">Find email</button><button id="verify-email">Verify email</button><button id="generate" class="primary">Draft with Maya</button></div><label for="stage">Relationship stage</label><select id="stage">${['new','ready','contacted','replied','meeting','closed','suppressed'].map(s=>`<option ${s===p.stage?'selected':''}>${s}</option>`).join('')}</select><label for="notes">Research and latest notes</label><textarea id="notes" class="notes">${esc(p.notes)}</textarea><label>To</label><p style="margin-top:9px">${esc(p.email||'Find an email first')}</p><label for="subject">Subject</label><input id="subject" value="${esc(p.subject)}" placeholder="Your introduction"><label for="body">Email draft</label><textarea id="body" placeholder="Generate or write a personal introduction.">${esc(p.body)}</textarea><div class="actions"><button id="save-draft">Save draft & notes</button><button id="compose" class="primary">Review in email app ↗</button></div><p class="small muted" style="margin-top:14px">${blocked?'This person is suppressed. Outreach is disabled.':'Opening a draft does not mark it sent. Update the stage after you send or hear back.'}</p></section>`;
 $('save-draft').onclick=()=>run(()=>save({type:'contact',id:p.id,stage:$('stage').value,notes:$('notes').value,subject:$('subject').value,body:$('body').value}));
 $('generate').onclick=()=>run(async()=>{if(blocked)throw Error('This contact is suppressed.');if(!leaveDraft())return;if(!confirm('Generate one email draft using OpenAI? This uses API credits.'))return;const j=await api('/draft',{id:p.id,confirm:true});$('subject').value=j.draft.subject;$('body').value=j.draft.body;notice('Draft ready for review. Press Save to keep it.');});
 const enrich=action=>run(async()=>{if(!leaveDraft())return;if(!confirm('Run this Hunter lookup? It may use Hunter credits.'))return;const j=await api('/hunter',{action,id:p.id,campaignId,confirm:true});state=j.state;render();notice('Hunter lookup complete.');});$('find-email').onclick=()=>enrich('find');$('verify-email').onclick=()=>enrich('verify');
 $('compose').onclick=()=>{if(blocked||$('stage').value==='suppressed')return notice('This contact is suppressed.',true);if(!p.email)return notice('Find an email first.',true);if(!['valid','accept_all'].includes(p.verification)&&!confirm('This address is not verified. Continue to your email app for review?'))return;location.href='mailto:'+encodeURIComponent(p.email)+'?subject='+encodeURIComponent($('subject').value)+'&body='+encodeURIComponent($('body').value);};
}
function addPerson(){modal('Add prospect',['name','email','company','domain','title','notes'].map(k=>field(k,k[0].toUpperCase()+k.slice(1))).join(''),data=>save({type:'import',campaignId,contact:Object.fromEntries(data)}));}
function renderCompanies(){const query=$('search').value.toLowerCase(),companies=state.companies.filter(c=>c.campaignId===campaignId&&[c.name,c.domain].join(' ').toLowerCase().includes(query));$('content').innerHTML='<div class="metrics">'+companies.map(c=>`<article class="metric-row"><div class="row spread"><div><h3>${esc(c.name||c.domain)}</h3><a href="https://${esc(c.domain)}" target="_blank" rel="noopener noreferrer">${esc(c.domain)} ↗</a><p class="muted small">${esc(c.description)}</p></div><button data-domain="${esc(c.domain)}">Find people</button></div></article>`).join('')+'</div>'+(!companies.length?'<div class="empty">Find companies with Hunter, then find the people behind them.</div>':'');document.querySelectorAll('[data-domain]').forEach(b=>b.onclick=()=>domainSearch(b.dataset.domain));}
function domainSearch(d){modal('Find people',field('domain','Company domain',d)+field('offset','Result offset (0 for first page)','0')+'<p class="muted small">Up to 25 contacts per lookup. Hunter credits may apply.</p>',async data=>{const j=await api('/hunter',{action:'domain',campaignId,domain:data.get('domain'),offset:Number(data.get('offset')),confirm:true});state=j.state;view='people';render();notice(`${j.result} new contacts imported.`);},'Find people');}
function renderResults(){const cards=state.campaigns.map(c=>{const p=state.contacts.filter(x=>x.campaignId===c.id),sent=p.filter(x=>['contacted','replied','meeting','closed'].includes(x.stage)).length,replies=p.filter(x=>['replied','meeting','closed'].includes(x.stage)).length;return `<article class="metric-row"><div class="row spread"><h3>${esc(c.name)}</h3><span class="badge">${esc(c.status)}</span></div><p class="muted" style="margin-top:9px">${sent} contacted · ${replies} replied · ${p.filter(x=>x.stage==='meeting').length} meetings · ${p.filter(x=>x.stage==='closed').length} closed</p><p class="small muted">${sent?Math.round(replies/sent*100)+'% recorded reply rate':'No recorded outreach yet'}</p></article>`;});$('content').innerHTML='<p class="muted small" style="margin-bottom:14px">Results reflect your recorded stages. Mail delivery and replies are not automatically synchronized.</p><div class="metrics">'+cards.join('')+'</div>';}
export function parseCSV(value){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<value.length;i++){const c=value[i];if(c==='"'){if(quoted&&value[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if(c==='\n'&&!quoted){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV has an unclosed quoted field.');if(cell||row.length){row.push(cell);rows.push(row);}return rows;}
function exportCSV(){const rows=[['Name','Email','Company','Domain','Title','Stage','Verification','Notes','Subject','Body'],...contacts().map(p=>[p.name,p.email,p.company,p.domain,p.title,p.stage,p.verification,p.notes,p.subject,p.body])];const safe=v=>'"'+(/^[=+@\-\t\r]/.test(String(v))?"'":'')+String(v??'').replace(/"/g,'""')+'"';const blob=new Blob([rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='maya-outbound.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('new-campaign').onclick=()=>editCampaign();$('edit-campaign').onclick=()=>editCampaign(campaign());$('search').onchange=()=>{if(leaveDraft())render();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(!leaveDraft())return;view=b.dataset.view;render();});
$('connections').onclick=()=>modal('Connections',field('sheetId','Google Sheet URL or ID',state.settings.sheetId)+field('tab','Exact tab name',state.settings.tab)+field('business','Studio facts Maya may use in drafts',state.settings.business,'textarea')+'<p class="small muted" style="margin-top:14px">Share the sheet with your Cloud Run service account. Hunter credentials stay on the server; never paste a key here.</p>',data=>save({type:'settings',...Object.fromEntries(data)}));
$('import').onclick=()=>{if(!leaveDraft())return;if(!campaign())return notice('Create a campaign first.',true);modal('Import prospects','<label>Source</label><select name="source"><option value="sheet">Connected Google Sheet</option><option value="csv">Paste CSV</option><option value="domain">Hunter company domain</option></select>'+field('csv','CSV with headers: Name, Email, Company, Domain, Title, Notes','','textarea')+field('domain','Company domain (Hunter only)')+'<p class="muted small">Sheet import reads up to 1,000 rows. Duplicate email addresses within a campaign are skipped. Hunter lookup may use credits.</p>',async data=>{let j;if(data.get('source')==='sheet')j=await api('/sheets',{campaignId});else if(data.get('source')==='domain')j=await api('/hunter',{action:'domain',domain:data.get('domain'),campaignId,confirm:true});else j=await api('/save',{type:'import',rows:parseCSV(data.get('csv')),campaignId});state=j.state;render();notice(`${j.result??0} new prospects imported.`);},'Import');};
$('discover').onclick=()=>{if(!leaveDraft())return;if(!campaign())return notice('Create a campaign first.',true);modal('Discover companies',field('query','Describe your target companies',campaign()?.audience,'textarea')+field('offset','Result offset (0 for first page)','0'),async data=>{const j=await api('/hunter',{action:'discover',query:data.get('query'),offset:Number(data.get('offset')),campaignId});state=j.state;view='companies';render();notice(`${j.found} companies returned.`);},'Search Hunter');};
$('close-modal').onclick=$('cancel-modal').onclick=()=>$('modal').close();$('reload').onclick=()=>run(load);
window.addEventListener('storage',e=>{if(e.key==='maya_admin_tok'&&token()!==session){state={campaigns:[],contacts:[],companies:[],settings:{}};campaignId=selected='';$('modal').close();render();run(load);}});
load();

$('research').onclick=()=>run(async()=>{
  const c=campaign();if(!c)throw Error('Create a campaign first.');
  if(!confirm('Research this market with Maya and web search? This uses OpenAI credits.'))return;
  notice('Maya is researching your audience and competitors…');
  const j=await api('/research',{campaignId:c.id,confirm:true});
  modal('Maya market research',field('competitors','Review research before saving',j.research,'textarea'),data=>save({type:'campaign',...c,competitors:data.get('competitors')}));
  notice('Research ready. Review sources and save what is useful.');
});
