import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source=readFileSync(new URL('../docs/server/server.js',import.meta.url),'utf8');
const start=source.indexOf("app.get('/api/admin/models'");
const route=source.slice(start,source.indexOf('\n});',start)+4);
let handler;
const context={app:{get:(path,auth,fn)=>{assert.equal(path,'/api/admin/models');handler=fn;}},requireAuthHeader:()=>{},requireAdmin:async req=>{if(!req.owner)throw Object.assign(Error('unauthorized'),{status:403});},process:{env:{OPENAI_API_KEY:'fixture-secret',K_SERVICE:'fixture-service',CRM_VERTEX_LOCATION:'global',PHONE_REALTIME_MODEL:'fixture-phone'}},crmAI:{connected:()=>[{provider:'openai',model:'fixture-crm',connected:true,transport:'api'},{provider:'gemini',model:'fixture-gemini',connected:true,transport:'vertex'},{provider:'anthropic',model:'fixture-legacy',connected:false,transport:'api'}]},MODEL_TERRA:'fixture-text',MODEL_SOL:'fixture-admin',MODEL_LUNA:'fixture-text',IMAGE_MODEL:'fixture-image',NANO_BANANA_MODEL:'fixture-vertex-image',VERTEX_LOCATION:'us-central1',REALTIME_MODEL:'fixture-web-voice'};
vm.runInNewContext(route,context);
const response=()=>({code:200,headers:{},set(k,v){this.headers[k]=v;return this;},status(v){this.code=v;return this;},json(v){this.body=v;return this;}});
const denied=response();await handler({},denied);assert.equal(denied.code,403);assert.equal(denied.body.error,'unauthorized');
const res=response();await handler({owner:true},res);assert.equal(res.headers['Cache-Control'],'no-store');assert.equal(res.body.models['Phone voice'],'fixture-phone');
assert.equal(res.body.connections.length,3);assert.equal(res.body.images.length,2);
assert.equal(res.body.connections.find(x=>x.provider==='gemini').transport,'vertex');assert.match(res.body.connections.find(x=>x.provider==='gemini').endpoint,/locations\/global\/publishers\/google/);
assert.equal(res.body.connections.find(x=>x.provider==='openai').endpoint,'https://api.openai.com/v1/responses');assert.equal(res.body.connections[0].endpoint,'https://api.openai.com/v1/chat/completions');
assert.equal(res.body.images[1].configured,true);assert.match(res.body.images[1].endpoint,/us-central1-aiplatform/);
assert.doesNotMatch(JSON.stringify(res.body),/fixture-secret|fixture-service|fixture-legacy/);
context.process.env={};const unconfigured=response();await handler({owner:true},unconfigured);assert.equal(unconfigured.body.connections[0].configured,false);assert.equal(unconfigured.body.images[0].configured,false);assert.equal(unconfigured.body.images[1].configured,false);
console.log('Authenticated model metadata reports actual transports/endpoints, preserves voice overrides and omits secrets.');
