import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {readFileSync} from 'node:fs';
import {extname,resolve} from 'node:path';
const root=resolve(new URL('..',import.meta.url).pathname);
const browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||process.env.CHROMIUM_PATH||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':'/opt/pw-browsers/chromium')});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let savedPost=null;
await page.route('**/*',async r=>{const u=new URL(r.request().url());if(!['maya.test','maya.manasiyo.com'].includes(u.hostname))return r.abort();if(u.pathname==='/api/design')return r.fulfill({json:{}});if(u.pathname==='/api/admin/design'){savedPost={header:r.request().headers()['authorization'],body:r.request().postDataJSON()};return r.fulfill({json:{ok:true}});}try{const p=resolve(root,'.'+u.pathname);if(!p.startsWith(root+'/'))return r.abort();await r.fulfill({body:readFileSync(p),contentType:({'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'})[extname(p)]||'text/plain'});}catch{await r.abort();}});
try{
 await page.goto('https://maya.test/aesthetics/aesthetic-control.html');await page.locator('[data-category="H4"] .type-row').first().waitFor();
 assert.match(await page.title(),/MAYA Aesthetic Control/);
 assert.equal(await page.locator('.type-group').count(),8);
 assert.deepEqual(await page.locator('.type-group').evaluateAll(es=>es.map(e=>e.dataset.category)),['H1','H2','H3','H4','P1','P2','P3','P4']);
 assert.equal(await page.locator('[data-type="dashboard"]').getAttribute('data-type'),'dashboard');
 assert.equal(await page.locator('[data-type="dashboard"] .type-example').evaluate(e=>getComputedStyle(e).fontSize),'14px');
 assert.equal(await page.locator('[data-type="drawer"] .type-example').evaluate(e=>getComputedStyle(e).fontSize),'20px');
 const legacy=await page.evaluate(()=>{const old=structuredClone(window.MayaTypographyControls.defaults);old.type.P5={size:8,weight:400,color:'gray'};old.type.P4={size:10,weight:350,color:'white'};old.type.P3={size:12,weight:400,color:'gray'};return window.MayaTypographyControls.normalize(old);});
 assert.equal(legacy.type.P3.weight,350);assert.equal(legacy.type.P4.size,8);assert.equal(legacy.type.P5,undefined);
 assert.equal(await page.locator('.type-row').count(),8);
 await page.locator('.finish-choice').filter({hasText:'Liquid'}).click();
 const liquid=await page.locator('.finish-sample .maya-pill').nth(1).evaluate(e=>getComputedStyle(e).borderColor);
 const clear=await page.locator('.finish-sample .maya-pill').nth(2).evaluate(e=>getComputedStyle(e).borderColor);
 assert.notEqual(liquid,clear);
 await page.locator('.finish-choice').filter({hasText:'Current'}).click();
 await page.locator('.finish-controls summary').click();
 await page.getByRole('slider',{name:'Transparency',exact:true}).fill('60');
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('.icon-row .maya-icon-button')).backgroundColor.includes('0.4'));
 assert.match(await page.locator('.icon-row .maya-icon-button').first().evaluate(e=>getComputedStyle(e).backgroundColor),/0.4/);
 await page.locator('.finish-controls summary').click();
 await page.locator('.overlay-controls summary').click();
 await page.getByRole('slider',{name:'Fill',exact:true}).fill('35');
 assert.match(await page.locator('#panels .maya-surface').first().evaluate(e=>getComputedStyle(e).backgroundColor),/0.35/);
 await page.locator('.overlay-controls summary').click();

 assert.equal(await page.locator('#gallery > section').first().getAttribute('id'),'pill-preview');
 assert.equal(await page.locator('#pill-colors .status-example').count(),5);
 assert.equal(await page.locator('#status-reference,#source-styles,#pages,#icons').count(),0);
 assert.ok(!(await page.locator('body').innerText()).includes('glossary'));
 assert.equal(await page.locator('[data-category="H1"] .type-example').evaluate(e=>getComputedStyle(e).textTransform),'uppercase');
 assert.equal(await page.locator('[data-category="H2"] .type-example').evaluate(e=>getComputedStyle(e).textTransform),'none');
 await page.locator('[data-category="H3"] .type-editor summary').click();
 await page.locator('[data-category="H3"] [data-field="font"]').selectOption('cormorant');
 await page.locator('[data-category="H3"] [data-field="case"]').selectOption('uppercase');
 assert.match(await page.locator('[data-category="H3"] .type-example').evaluate(e=>getComputedStyle(e).fontFamily),/Cormorant/);
 assert.equal(await page.locator('[data-category="H3"] .type-example').evaluate(e=>getComputedStyle(e).textTransform),'uppercase');
 await page.locator('[data-category="H3"] .type-editor summary').click();
 assert.equal(await page.locator('.type-row .type-appearance,.type-row .type-spacing').count(),0);
 assert.equal(await page.locator('.category-setting').count(),8);
 assert.equal(await page.locator('.type-align[aria-pressed="true"]').count(),8);
 assert.equal(await page.locator('[data-type="brand"] .type-example').evaluate(e=>getComputedStyle(e).textAlign),'center');
 await page.locator('[data-category="P1"] .type-editor summary').click();
 await page.locator('[data-category="P1"] [data-field="color"]').selectOption('white');
 await page.locator('[data-category="P1"] .type-editor summary').click();
 await page.getByRole('button',{name:'Center align P1',exact:true}).click();
 assert.equal(await page.locator('[data-type="paragraph"] .type-example').evaluate(e=>getComputedStyle(e).textAlign),'left');
 assert.equal(await page.locator('#table-preview td[data-preview-category="P1"]').first().evaluate(e=>getComputedStyle(e).textAlign),'left');
 await page.getByRole('button',{name:'Center align P1',exact:true}).click();
 await page.locator('.housing-editor summary').click();
 await page.locator('[data-editor-field="radius"]').fill('20');
 await page.locator('[data-editor-field="fill"]').fill('45');
 await page.locator('[data-category="H1"] .type-editor summary').click();
 assert.equal(await page.locator('[data-category="H1"] .type-editor-fields').evaluate(e=>getComputedStyle(e).borderRadius),'20px');
 assert.equal(await page.locator('[data-category="H1"] .type-row').first().evaluate(e=>getComputedStyle(e).paddingTop),'6px');
 await page.locator('[data-category="H1"] .type-editor summary').click();
 assert.equal(await page.locator('#table-preview tbody tr').count(),2);
 await page.locator('[data-category="H4"] .type-editor summary').click();
 await page.locator('[data-category="H4"] [data-field="size"]').fill('12');
 assert.equal(await page.locator('[data-type="dashboard"] .type-example').evaluate(e=>getComputedStyle(e).fontSize),'12px');
 await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#feedback').textContent.includes('Saved locally'));assert.match(await page.locator('#feedback').textContent(),/Saved locally/);
 await page.reload();await page.locator('[data-category="H4"] .type-row').first().waitFor();
 assert.equal(await page.locator('[data-type="dashboard"] .type-example').evaluate(e=>getComputedStyle(e).fontSize),'12px');
 assert.equal(await page.locator('[data-editor-field="radius"]').inputValue(),'20');
 assert.equal(await page.locator('[data-category="H3"] [data-field="case"]').inputValue(),'uppercase');
 assert.equal(await page.locator('[data-category="H3"] [data-field="font"]').inputValue(),'cormorant');
 assert.equal(await page.locator('#table-preview td[data-preview-category="P1"]').first().evaluate(e=>getComputedStyle(e).textAlign),'center');
 await page.goto('https://maya.test/backend/status.html',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>!!document.getElementById('maya-typography-control-style'));
 assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--maya-type-H4-size').trim()),'12px');
 assert.equal(await page.evaluate(()=>{const host=document.querySelector('#adm-mkt');const node=document.createElement('div');node.className='bl-step';node.innerHTML='<div class="v">12</div>';host.append(node);const size=getComputedStyle(node.firstChild).fontSize;node.remove();return size;}),'12px');
 assert.equal(await page.locator('h2.grp').first().evaluate(e=>getComputedStyle(e).textTransform),'uppercase');
 assert.match(await page.locator('h2.grp').first().evaluate(e=>getComputedStyle(e).fontFamily),/Cormorant/);
 assert.match(await page.evaluate(()=>{const n=document.createElement('button');n.className='maya-icon-button';document.body.append(n);const color=getComputedStyle(n).backgroundColor;n.remove();return color;}),/0.4/);
 assert.equal(await page.evaluate(()=>{const n=document.createElement('p');n.textContent='Body preview';document.body.append(n);const c=getComputedStyle(n).color;n.remove();return c;}),'rgb(255, 255, 255)');
 const designLink=page.getByRole('link',{name:'Aesthetic Control',exact:true});
 assert.equal(await designLink.getAttribute('href'),'/aesthetics/aesthetic-control.html');
 assert.equal(await designLink.evaluate(e=>getComputedStyle(e).borderRadius),'100px');
 await page.goto('https://maya.test/frontend/index.html',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>!!document.getElementById('maya-typography-control-style'));
 assert.equal(await page.locator('#brand-title').evaluate(e=>getComputedStyle(e).fontSize),'24px');
 await page.goto('https://maya.test/backend/outbound.html',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>!!document.getElementById('maya-typography-control-style'));
 assert.equal(await page.evaluate(()=>{const n=document.createElement('div');n.className='stat';n.innerHTML='<strong>262</strong>';document.body.append(n);const size=getComputedStyle(n.firstChild).fontSize;n.remove();return size;}),'12px');
 await page.goto('https://maya.test/aesthetics/aesthetic-control.html');await page.locator('#save').waitFor();
 await page.locator('#reset').click();
 // Negative left overflow does not increase scrollWidth: inspect actual bounds.
 await page.locator('#pill-preview > .review-fold > summary').click();
 await page.locator('[data-category="H1"] .type-align').click();
 await page.locator('.housing-editor summary').click();
 await page.locator('[data-editor-field="padding"]').fill('20');
 await page.locator('[data-editor-field="padding"]').dispatchEvent('input');
 for(const width of [320,390,420,650,700,701,768,1024,1100,1440,1920]){
  await page.setViewportSize({width,height:844});
  for(const role of ['H1','H2','H3','H4','P1','P2','P3','P4']){
   const editor=page.locator(`[data-category="${role}"] .type-editor`);
   await editor.locator('summary').click();
   const geometry=await editor.locator('.type-editor-fields').evaluate(panel=>{
    const section=panel.closest('.preview-section').getBoundingClientRect();
    const popup=panel.getBoundingClientRect();
    return {left:popup.left,right:popup.right,sectionLeft:section.left,sectionRight:section.right,
     controls:[...panel.querySelectorAll('input,select')].map(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,width:r.width};})};
   });
   assert.ok(geometry.left>=Math.max(0,geometry.sectionLeft)&&geometry.right<=Math.min(width,geometry.sectionRight),`${role} popup outside section at ${width}: ${JSON.stringify(geometry)}`);
   assert.ok(geometry.controls.every(r=>r.width>0&&r.left>=geometry.left&&r.right<=geometry.right),`${role} controls outside popup at ${width}`);
   await editor.locator('[data-field="case"]').selectOption('none');
   if(width===1100&&role==='H1')await page.screenshot({path:'/private/tmp/maya-dropdown-fixed.png'});
   await editor.locator('summary').click();
  }
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);
 }
 await page.locator('#reset').click();
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'/private/tmp/maya-typography-controls.png',fullPage:true});
 await page.goto('https://maya.manasiyo.com/aesthetics/aesthetic-control.html');await page.locator('#save').waitFor();
 await page.evaluate(()=>localStorage.setItem('maya_admin_tok','test-owner-token'));
 await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#feedback').textContent.includes('Saved across MAYA pages'));
 const {validDesign}=await import('../docs/server/design-config.mjs');assert.equal(validDesign(savedPost.body),true);assert.equal(savedPost.body.editor.radius,12);assert.equal(savedPost.body.type.P1.align,'center');assert.equal(savedPost.header,'Bearer test-owner-token');assert.deepEqual(Object.keys(savedPost.body.type),['H1','H2','H3','H4','P1','P2','P3','P4']);
 assert.deepEqual(errors.filter(e=>!e.includes('Firebase')&&!e.includes('google')),[]);
 console.log('Typography Controls passed: role counts, descending roles, edit/save/reload, Admin application, eleven widths with all popup and control bounds.');
}finally{await browser.close();}
