import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {readFileSync} from 'node:fs';
import {extname,resolve} from 'node:path';
const root=resolve(new URL('..',import.meta.url).pathname);
const browser=await chromium.launch({executablePath:process.env.PW_CHROMIUM||process.env.CHROMIUM_PATH||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':'/opt/pw-browsers/chromium')});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let savedPost=null;
await page.route('**/*',async r=>{const u=new URL(r.request().url());if(!['maya.test','maya.manasiyo.com'].includes(u.hostname))return r.abort();if(u.pathname==='/api/design')return r.fulfill({json:{}});if(u.pathname==='/api/admin/design'){savedPost={header:r.request().headers()['authorization'],body:r.request().postDataJSON()};return r.fulfill({json:{ok:true}});}try{const p=resolve(root,'.'+u.pathname);if(!p.startsWith(root+'/'))return r.abort();await r.fulfill({body:readFileSync(p),contentType:({'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.png':'image/png','.svg':'image/svg+xml'})[extname(p)]||'text/plain'});}catch{await r.abort();}});
try{
 await page.goto('https://maya.test/aesthetics/aesthetic-control.html');await page.locator('[data-category="H4"] .type-row').first().waitFor();
 assert.match(await page.title(),/MAYA Aesthetic Control/);
 assert.equal(await page.locator('.type-group').count(),8);
 assert.ok(await page.locator('.type-category').evaluateAll(es=>es.every(e=>/^[HP][1-4] \(\d+\)$/.test(e.textContent))),'Every role shows an authored usage count');
 assert.equal(await page.locator('.restore-editor').count(),15,'Each editor plus selected cell formatting has a restore');
 assert.equal(await page.locator('.icon-row [aria-label="Download"]').count(),0,'Unused icon preview removed');
 assert.deepEqual(await page.locator('.type-group').evaluateAll(es=>es.map(e=>e.dataset.category)),['H1','H2','H3','H4','P1','P2','P3','P4']);
 assert.equal(await page.locator('[data-type="dashboard"]').getAttribute('data-type'),'dashboard');
 assert.equal(await page.locator('[data-type="dashboard"] .type-example').evaluate(e=>getComputedStyle(e).fontSize),'14px');
 assert.equal(await page.locator('[data-type="drawer"] .type-example').evaluate(e=>getComputedStyle(e).fontSize),'20px');
 const legacy=await page.evaluate(()=>{const old=structuredClone(window.MayaTypographyControls.defaults);old.type.P5={size:8,weight:400,color:'gray'};old.type.P4={size:10,weight:350,color:'white'};old.type.P3={size:12,weight:400,color:'gray'};return window.MayaTypographyControls.normalize(old);});
 const legacyCells=await page.evaluate(()=>{const d=structuredClone(window.MayaTypographyControls.defaults);d.table.cells={'stage-0':{...d.table.header,align:'right'}};return window.MayaTypographyControls.normalize(d).table;});assert.equal(legacyCells.columns[1].align,'right');assert.deepEqual(legacyCells.cells,{});
 assert.equal(legacy.type.P3.weight,350);assert.equal(legacy.type.P4.size,8);assert.equal(legacy.type.P5,undefined);
 assert.equal(await page.locator('.type-row').count(),8);
 await page.locator('.finish-choice').filter({hasText:'Liquid'}).click();
 assert.match(await page.locator('.finish-choice[aria-pressed=true]').innerText(),/Liquid ✓/);
 const liquid=await page.locator('.finish-sample .maya-pill').nth(1).evaluate(e=>getComputedStyle(e).borderColor);
 const clear=await page.locator('.finish-sample .maya-pill').nth(2).evaluate(e=>getComputedStyle(e).borderColor);
 assert.notEqual(liquid,clear);
 await page.locator('.finish-choice').filter({hasText:'Current'}).click();
 await page.locator('.finish-controls summary').click();
 await page.getByRole('slider',{name:'Transparency',exact:true}).fill('60');
 await page.waitForFunction(()=>getComputedStyle(document.querySelector('.icon-row .maya-icon-button')).backgroundColor.includes('0.4'));
 assert.match(await page.locator('.icon-row .maya-icon-button').first().evaluate(e=>getComputedStyle(e).backgroundColor),/0.4/);
 await page.locator('.finish-controls summary').click();
 await page.locator('.overlay-controls summary').click();
 await page.getByRole('slider',{name:'Fill',exact:true}).fill('35');
 assert.match(await page.locator('#pill-preview').first().evaluate(e=>getComputedStyle(e).backgroundColor),/0.35/);
 await page.getByRole('slider',{name:'Padding X',exact:true}).fill('24');
 await page.getByRole('slider',{name:'Padding Y',exact:true}).fill('14');
 assert.equal(await page.locator('#pill-preview').first().evaluate(e=>getComputedStyle(e).padding),'14px 24px');
 await page.locator('.overlay-controls summary').click();

 await page.locator('.overlay-controls summary').click();
 assert.equal(await page.locator('#pill-preview.show-padding').count(),1);
 assert.equal(await page.locator('#pill-preview').first().evaluate(e=>getComputedStyle(e,'::after').borderTopWidth),'14px');
 assert.equal(await page.locator('#pill-preview').first().evaluate(e=>getComputedStyle(e,'::after').borderLeftWidth),'24px');
 await page.locator('[data-editor="inner"] summary').click();
 await page.locator('[data-editor="inner"] [data-field="paddingX"]').fill('22');
 assert.equal(await page.locator('#panels .inner-panel.show-padding').count(),2);
 assert.equal(await page.locator('#panels .inner-panel>h3').count(),2,'Panel heading is inside its padded content');
 assert.equal(await page.locator('#panels>.context-grid>.inner-panel').evaluateAll(es=>es.length===2&&es.every(e=>e.querySelector('h3')&&e.querySelector('.maya-metric'))),true);
 assert.equal(await page.locator('#panels .inner-panel').first().evaluate(e=>getComputedStyle(e,'::after').borderLeftWidth),'22px');
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#gallery .show-padding'));
 await page.locator('.control-size-editor summary').click();await page.locator('[data-field="iconSize"]').fill('36');await page.locator('[data-field="dropdownHeight"]').fill('32');
 assert.equal(await page.locator('.icon-row .maya-icon-button').first().evaluate(e=>getComputedStyle(e).width),'36px');
 assert.equal(await page.locator('.dropdown-preview').evaluate(e=>getComputedStyle(e).minHeight),'32px');
 await page.locator('.gallery-header h1').click();
 assert.equal(await page.locator('#save').evaluate(e=>getComputedStyle(e).backgroundColor),await page.locator('#buttons>.preview-row .maya-pill').first().evaluate(e=>getComputedStyle(e).backgroundColor));
 assert.equal(await page.locator('#gallery > section').first().getAttribute('id'),'pill-preview');
 assert.equal(await page.locator('#pill-colors .status-example').count(),5);
 assert.equal(await page.locator('#status-reference,#source-styles,#pages,#icons').count(),0);
 assert.ok(!(await page.locator('body').innerText()).includes('glossary'));
 assert.equal(await page.locator('[data-category="H1"] .type-example').evaluate(e=>getComputedStyle(e).textTransform),'uppercase');
 assert.equal(await page.locator('[data-category="H2"] .type-example').evaluate(e=>getComputedStyle(e).textTransform),'none');
 await page.locator('[data-category="H3"] .type-editor summary').click();
 await page.locator('[data-category="H3"] [data-field="font"]').selectOption('cormorant');
 await page.locator('[data-category="H3"] [data-field="case"]').selectOption('uppercase');
 assert.match(await page.locator('[data-category="H3"] .type-example').evaluate(e=>getComputedStyle(e).fontFamily),/Cormorant/);
 assert.equal(await page.locator('[data-category="H3"] .type-example').evaluate(e=>getComputedStyle(e).textTransform),'uppercase');
 await page.locator('[data-category="H3"] .type-editor summary').click();
 assert.equal(await page.locator('.type-row .type-appearance,.type-row .type-spacing').count(),0);
 assert.equal(await page.locator('.category-setting').count(),8);
 assert.equal(await page.locator('.type-align,.housing-editor,#reset,.gallery-header nav').count(),0);
 assert.equal(await page.locator('[data-type="brand"] .type-example').evaluate(e=>getComputedStyle(e).textAlign),'center');
 const edit=async(role,field,value)=>{const group=page.locator(`[data-category="${role}"] .type-editor`);if(!await group.evaluate(e=>e.open))await group.locator('summary').click();await group.locator(`[data-field="${field}"]`).selectOption(value);};
 await edit('P1','color','white');await edit('P1','align','right');
 assert.equal(await page.locator('[data-type="paragraph"] .type-example').evaluate(e=>getComputedStyle(e).textAlign),'right');
 await edit('P1','align','center');
 await page.locator('.gallery-header h1').click();
 assert.equal(await page.locator('.type-editor[open]').count(),0,'Outside click dismisses');
 await edit('H1','align','right');await page.keyboard.press('Escape');
 assert.equal(await page.locator('.type-editor[open]').count(),0,'Escape dismisses');
 const surface=async(id,field,value)=>{const group=page.locator(`[data-editor="${id}"] .type-editor`);if(!await group.evaluate(e=>e.open)){await page.keyboard.press('Escape');await group.locator('summary').click();}const input=group.locator(`[data-field="${field}"]`);if(await input.evaluate(e=>e.tagName==='SELECT'))await input.selectOption(value);else await input.fill(value);};
 await surface('inner','paddingX','30');await surface('inner','paddingY','20');await surface('inner','width','80');
 assert.equal(await page.locator('.inner-panel').first().evaluate(e=>getComputedStyle(e).padding),'20px 30px');
 await surface('filter','width','330');await surface('filter','paddingX','24');
 const cell=async(selector,field,value)=>{await page.locator('#table-preview '+selector).first().click();const input=page.locator('#cell-format-toolbar [data-field="'+field+'"]');if(await input.evaluate(e=>e.tagName==='SELECT'))await input.selectOption(value);else await input.fill(value);};
 assert.equal(await page.locator('#table-editors .type-editor').count(),1,'Only whole-table Edit remains');
 await surface('table','background','black');await surface('table','fill','100');
 await cell('th[data-col="stage"]','background','black');await cell('td[data-col="name"]','background','black');
 assert.equal(await page.locator('#table-preview table').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(0, 0, 0)');
 assert.equal(await page.locator('#table-preview .lead-open').first().evaluate(e=>[...e.children].map(n=>n.tagName==='TIME'?'date':n.className).join(',')),'lead-identity,date,category-badge');
 await cell('th[data-col="stage"]','background','blue');await cell('th[data-col="stage"]','opacity','80');await cell('th[data-col="stage"]','font','cormorant');await cell('th[data-col="stage"]','size','14');
 assert.equal(await page.locator('#cell-selection').innerText(),'Top row');assert.equal(await page.locator('#table-preview .cell-selected').count(),3);
 await cell('td[data-col="name"]','background','pink');await cell('td[data-col="name"]','opacity','60');await cell('td[data-col="name"]','font','cormorant');await cell('td[data-col="name"]','align','right');await cell('td[data-col="name"]','vertical','top');
 assert.equal(await page.locator('#cell-selection').innerText(),'First column');assert.equal(await page.locator('#table-preview .cell-selected').count(),2);
 await cell('td[data-col="note"]','size','15');
 assert.equal(await page.locator('#cell-selection').innerText(),'Third column');
 assert.equal(await page.locator('#table-preview td[data-col="note"]').nth(1).evaluate(e=>getComputedStyle(e).fontSize),'15px','Every body row follows its column');
 await page.locator('#cell-format-toolbar .restore-editor').click();assert.equal(await page.locator('#table-preview td[data-col="note"]').first().evaluate(e=>getComputedStyle(e).fontSize),'12px');
 await cell('td[data-col="note"]','size','15');await surface('table','paddingY','14');
 assert.match(await page.locator('#table-preview th').first().evaluate(e=>getComputedStyle(e).backgroundColor),/0.8/);
 assert.match(await page.locator('#table-preview td[data-col="name"]').first().evaluate(e=>getComputedStyle(e).backgroundColor),/0.6/);
 assert.equal(await page.locator('#table-preview td[data-col="name"]').first().evaluate(e=>getComputedStyle(e).textAlign),'right');
 assert.equal(await page.locator('#table-preview td[data-col="note"]').first().evaluate(e=>getComputedStyle(e).fontSize),'15px');
 await page.locator('#table-preview th[data-col="name"]').click();assert.equal(await page.locator('#cell-selection').innerText(),'Top row + first column');assert.equal(await page.locator('#table-preview .cell-selected').count(),5);
 assert.equal(await page.locator('#table-preview tbody tr').count(),2);
 await cell('td[data-col="stage"]','align','right');assert.equal(await page.locator('#cell-selection').innerText(),'Second column');assert.equal(await page.locator('#table-preview .cell-selected').count(),2);assert.equal(await page.locator('#table-preview td[data-col="stage"]').nth(1).evaluate(e=>getComputedStyle(e).textAlign),'right');
 await cell('td[data-col="stage"]','align','center');await cell('td[data-col="stage"]','background','green');await cell('td[data-col="stage"]','opacity','50');assert.match(await page.locator('#table-preview td[data-col="stage"]').nth(1).evaluate(e=>getComputedStyle(e).backgroundColor),/0.5/);
 assert.equal(await page.locator('#panels .maya-surface').count(),0,'No intermediate outer wrapper');
 assert.equal(await page.locator('[data-category="H1"] .role-locations a').count(),14,'Every authored H1 is listed');
 assert.ok(await page.locator('[data-category="H1"] .type-setting').innerText().then(text=>text.toLowerCase().includes('app')&&text.toLowerCase().includes('status')));
 await page.locator('.gallery-header h1').click();
 await page.locator('[data-category="H4"] .type-editor summary').click();
 await page.locator('[data-category="H4"] [data-field="size"]').fill('12');
 assert.equal(await page.locator('[data-type="dashboard"] .type-example').evaluate(e=>getComputedStyle(e).fontSize),'12px');
 await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#feedback').textContent.includes('Saved locally'));assert.match(await page.locator('#feedback').textContent(),/Saved locally/);
 await page.reload();await page.locator('[data-category="H4"] .type-row').first().waitFor();
 assert.equal(await page.locator('[data-type="dashboard"] .type-example').evaluate(e=>getComputedStyle(e).fontSize),'12px');
 assert.equal(await page.locator('[data-category="H3"] [data-field="case"]').inputValue(),'uppercase');
 assert.equal(await page.locator('[data-category="H3"] [data-field="font"]').inputValue(),'cormorant');
 assert.equal(await page.locator('#table-preview td[data-col="stage"]').first().evaluate(e=>getComputedStyle(e).textAlign),'center');
 assert.equal(await page.locator('#table-preview td[data-col="note"]').first().evaluate(e=>getComputedStyle(e).fontSize),'15px');
 assert.equal(await page.locator('.inner-panel').first().evaluate(e=>getComputedStyle(e).padding),'20px 30px');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('maya-typography-controls-v1')).iconSize),36);
 await surface('inner','paddingX','10');await page.locator('[data-editor="inner"] .restore-editor').click();assert.equal(await page.locator('.inner-panel').first().evaluate(e=>getComputedStyle(e).padding),'20px 30px','Restore uses saved baseline after reload');
 await page.goto('https://maya.test/backend/status.html',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>!!document.getElementById('maya-typography-control-style'));
 assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--maya-type-H4-size').trim()),'12px');
 assert.equal(await page.evaluate(()=>{const host=document.querySelector('#adm-mkt');const node=document.createElement('div');node.className='bl-step';node.innerHTML='<div class="v">12</div>';host.append(node);const size=getComputedStyle(node.firstChild).fontSize;node.remove();return size;}),'12px');
 assert.equal(await page.locator('h2.grp').first().evaluate(e=>getComputedStyle(e).textTransform),'uppercase');
 assert.match(await page.locator('h2.grp').first().evaluate(e=>getComputedStyle(e).fontFamily),/Cormorant/);
 assert.match(await page.evaluate(()=>{const n=document.createElement('button');n.className='maya-icon-button';document.body.append(n);const color=getComputedStyle(n).backgroundColor;n.remove();return color;}),/0.4/);
 assert.equal(await page.evaluate(()=>{const n=document.createElement('p');n.textContent='Body preview';document.body.append(n);const c=getComputedStyle(n).color;n.remove();return c;}),'rgb(255, 255, 255)');
 const liveTable=await page.evaluate(async()=>{
  const table=document.querySelector('#leads-table');table.innerHTML='<tbody><tr><th>Full name</th><th>Status</th><th>Latest Notes</th></tr><tr><td class="lead-col-first" data-col="name"><button class="lead-open">Angela</button></td><td data-col="stage"><span class="status-pill">Not contacted</span></td><td data-col="note"><div class="lead-note-vp"><span>Fixture note</span></div></td></tr></tbody>';
  await new Promise(resolve=>requestAnimationFrame(resolve));
  const note=getComputedStyle(table.querySelector('td[data-col="note"] .lead-note-vp>span'));
  const name=getComputedStyle(table.querySelector('.lead-open'));
  const filter=document.createElement('div');filter.className='lead-status-menu';document.body.append(filter);const width=getComputedStyle(filter).width;filter.remove();
  return {noteSize:note.fontSize,nameFont:name.fontFamily,nameAlign:name.textAlign,header:getComputedStyle(table.querySelector('th')).backgroundColor,filterWidth:width,inner:getComputedStyle(document.querySelector('#leads-fold .panel')).padding};
 });
 assert.equal(liveTable.noteSize,'15px');assert.match(liveTable.nameFont,/Cormorant/);assert.equal(liveTable.nameAlign,'right');assert.match(liveTable.header,/0.8/);assert.equal(liveTable.filterWidth,'330px');assert.equal(liveTable.inner,'20px 30px');
 const designLink=page.getByRole('link',{name:'Aesthetic Control',exact:true});
 assert.equal(await designLink.getAttribute('href'),'/aesthetics/aesthetic-control.html');
 assert.equal(await designLink.evaluate(e=>getComputedStyle(e).borderRadius),'100px');
 await page.goto('https://maya.test/frontend/index.html',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>!!document.getElementById('maya-typography-control-style'));
 assert.equal(await page.locator('#brand-title').evaluate(e=>getComputedStyle(e).fontSize),'24px');
 await page.goto('https://maya.test/backend/outbound.html',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>!!document.getElementById('maya-typography-control-style'));
 assert.equal(await page.evaluate(()=>{const n=document.createElement('div');n.className='stat';n.innerHTML='<strong>262</strong>';document.body.append(n);const size=getComputedStyle(n.firstChild).fontSize;n.remove();return size;}),'12px');
 await page.goto('https://maya.test/aesthetics/aesthetic-control.html');await page.locator('#save').waitFor();
 await page.evaluate(()=>localStorage.clear());await page.reload();await page.locator('#save').waitFor();
 // Negative left overflow does not increase scrollWidth: inspect actual bounds.
 await page.locator('#pill-preview > .review-fold > summary').click();
 await page.evaluate(()=>document.documentElement.style.setProperty('--type-editor-padding','20px'));
 for(const width of [320,390,420,650,700,701,768,1024,1100,1440,1920]){
  await page.setViewportSize({width,height:844});
  for(const role of ['H1','H2','H3','H4','P1','P2','P3','P4']){
   const editor=page.locator(`[data-category="${role}"] .type-editor`);
   await editor.locator('summary').click();
   const geometry=await editor.locator('.type-editor-fields').evaluate(panel=>{
    const section=panel.closest('.preview-section').getBoundingClientRect();
    const popup=panel.getBoundingClientRect();
    return {left:popup.left,right:popup.right,sectionLeft:section.left,sectionRight:section.right,
     controls:[...panel.querySelectorAll('input,select')].map(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,width:r.width};})};
   });
   assert.ok(geometry.left>=Math.max(0,geometry.sectionLeft)&&geometry.right<=Math.min(width,geometry.sectionRight),`${role} popup outside section at ${width}: ${JSON.stringify(geometry)}`);
   assert.ok(geometry.controls.every(r=>r.width>0&&r.left>=geometry.left&&r.right<=geometry.right),`${role} controls outside popup at ${width}`);
   await editor.locator('[data-field="case"]').selectOption('none');
   if(width===1100&&role==='H1')await page.screenshot({path:'/private/tmp/maya-dropdown-fixed.png'});
   await editor.locator('summary').click();
  }
  await page.locator('#pill-preview > .review-fold').evaluate(e=>e.open=true);
  const outerEditor=page.locator('.overlay-controls');await outerEditor.locator('summary').click();
  assert.ok(await outerEditor.locator('.type-editor-fields').evaluate(e=>{const r=e.getBoundingClientRect(),a=e.parentElement.querySelector('summary').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&a.left<=r.right&&a.right>=r.left;}),'Outer editor anchor '+width);await page.keyboard.press('Escape');
  for(const id of ['inner','filter','table']){
   const editor=page.locator(`[data-editor="${id}"] .type-editor`);await editor.locator('summary').click();
   const fits=await editor.locator('.type-editor-fields').evaluate(e=>{const r=e.getBoundingClientRect(),a=e.parentElement.querySelector('summary').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&a.left<=r.right&&a.right>=r.left&&Math.min(Math.abs(r.top-a.bottom),Math.abs(a.top-r.bottom))<=8&&getComputedStyle(e).backgroundColor==='rgb(0, 0, 0)'&&[...e.querySelectorAll('input,select')].every(c=>{const b=c.getBoundingClientRect();return b.left>=r.left&&b.right<=r.right;});});
   assert.ok(fits,`${id} popup/controls at ${width}`);
   assert.ok(await editor.locator('.type-editor-fields').evaluate(panel=>{const box=panel.getBoundingClientRect();return [...panel.querySelectorAll('input,select')].every(e=>{const b=e.getBoundingClientRect(),y=b.top+b.height/2;if(y<box.top||y>box.bottom)return true;const hit=document.elementFromPoint(b.left+b.width/2,y);return hit===e||e.contains(hit);});}),`${id} visible fields stay above the following section at ${width}`);
   await page.keyboard.press('Escape');
  }
  const sizeEditor=page.locator('.control-size-editor');await sizeEditor.locator('summary').click();assert.ok(await sizeEditor.locator('.type-editor-fields').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}),'Size editor fits '+width);await page.keyboard.press('Escape');
  await page.locator('#cell-format-toolbar').evaluate(e=>{const r=e.getBoundingClientRect();if(r.left<0||r.right>innerWidth)throw Error('Cell toolbar overflow');const fields=e.querySelector('.cell-format-fields');if(new Set([...fields.children].map(c=>Math.round(c.getBoundingClientRect().top))).size!==1)throw Error('Cell toolbar wraps');});
  await page.locator('#pill-preview > .review-fold').evaluate(e=>e.open=false);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+width);
 }
 await page.evaluate(()=>localStorage.clear());await page.reload();await page.locator('#save').waitFor();
 await page.setViewportSize({width:1440,height:1000});
 assert.equal(await page.locator('.panel-editors .surface-edit-row').evaluateAll(es=>new Set(es.map(e=>Math.round(e.getBoundingClientRect().top))).size),1,'Panel controls share one desktop row');
 assert.equal(await page.locator('#table-editors .surface-edit-row').evaluateAll(es=>new Set(es.map(e=>Math.round(e.getBoundingClientRect().top))).size),1,'Table controls share one desktop row');
 assert.equal(await page.locator('#table-preview .lead-open').first().evaluate(e=>new Set([...e.children].map(n=>Math.round(n.getBoundingClientRect().top+n.getBoundingClientRect().height/2))).size),1,'Name, date and category share one row');
 await page.screenshot({path:'/private/tmp/maya-typography-controls.png',fullPage:true});
 await page.goto('https://maya.manasiyo.com/aesthetics/aesthetic-control.html');await page.locator('#save').waitFor();
 await page.evaluate(()=>localStorage.setItem('maya_admin_tok','test-owner-token'));
 await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#feedback').textContent.includes('Saved across MAYA pages'));
 const {validDesign}=await import('../docs/server/design-config.mjs');const invalid=structuredClone(savedPost.body);invalid.table.cells={'note-100':{...invalid.table.header}};assert.equal(validDesign(invalid),false,'Cell row limits are validated');assert.equal(validDesign({...savedPost.body,table:{...savedPost.body.table,cells:{'note-0':{...savedPost.body.table.header}}}}),true);assert.equal(validDesign(savedPost.body),true,JSON.stringify(savedPost.body));assert.equal(savedPost.body.iconSize,28);assert.equal(savedPost.body.dropdownHeight,28);assert.equal(JSON.stringify(savedPost.body).includes("show-padding"),false);assert.equal(savedPost.body.editor.radius,12);assert.equal(savedPost.body.table.columns.length,3);assert.equal(savedPost.body.type.P1.align,'center');assert.equal(savedPost.header,'Bearer test-owner-token');assert.deepEqual(Object.keys(savedPost.body.type),['H1','H2','H3','H4','P1','P2','P3','P4']);
 assert.deepEqual(errors.filter(e=>!e.includes('Firebase')&&!e.includes('google')),[]);
 console.log('Typography Controls passed: role counts, descending roles, edit/save/reload, Admin application, eleven widths with all popup and control bounds.');
}finally{await browser.close();}
