import {chromium} from 'playwright';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,executablePath:process.env.PW_CHROMIUM});
try{
const page=await browser.newPage({viewport:{width:320,height:640}});const errors=[];page.on('pageerror',e=>errors.push(e.message));let enabled=false,added=false;
await page.route('**/*',async r=>{const p=new URL(r.request().url()).pathname;if(p==='/canon.css')return r.fulfill({contentType:'text/css',body:readFileSync('aesthetics/ui/maya-canon.css')});if(p==='/widget.js')return r.fulfill({contentType:'text/javascript; charset=utf-8',body:readFileSync('aesthetics/ui/owner-crm.js')});if(p.endsWith('/enable')){enabled=true;return r.fulfill({json:{ok:true}});}if(p.endsWith('/test-gemini'))return r.fulfill({json:{ok:true,model:'fixture-gemini',costUsd:.000001}});if(p.endsWith('/gmail-review'))return r.fulfill({json:{ok:true,candidates:[{id:'one',email:'pat@example.com',subject:'Suit',note:'<script>Untrusted</script>'}]}});if(p.endsWith('/gmail-add')){assert.deepEqual(r.request().postDataJSON(),{id:'one',name:'Pat'});added=true;return r.fulfill({json:{ok:true,name:'Pat'}});}if(p==='/api/admin/owner-crm')return r.fulfill({json:{enabled,mailboxes:[],gmailReady:false,numberEnding:'0100'}});return r.fulfill({contentType:'text/html; charset=utf-8',body:'<html data-maya-surface="dense"><link rel="stylesheet" href="/canon.css"><div id="drawer"><maya-owner-crm></maya-owner-crm></div><script>localStorage.setItem("maya_admin_tok","owner")</script><script src="/widget.js"></script>'});});
await page.goto('https://maya.test/');assert.equal(await page.locator('.test-gemini').count(),0,'No manual Gemini test control');await page.locator('#drawer').evaluate(e=>e.classList.add('msgs'));assert.equal(await page.locator('maya-owner-crm').isVisible(),false,'Owner tools cannot leak into Messages');await page.locator('#drawer').evaluate(e=>e.classList.remove('msgs'));await page.locator("summary").click();await page.getByText(/Setup needed/).waitFor();await page.getByRole('button',{name:'Enable my text commands'}).click();await page.getByText(/Text commands enabled/).waitFor();await page.getByRole('button',{name:'Review Gmail leads'}).click();await page.getByText('pat@example.com · Suit').click();await page.getByLabel('Name for pat@example.com').fill('Pat');await page.getByRole('button',{name:'Add to Leads'}).click();await page.getByText(/Added Pat/).waitFor();assert.ok(added);assert.deepEqual(errors,[]);
console.log('Owner tools: setup, removed manual Gemini button, escaped Gmail review and lead add flows pass.');
}finally{await browser.close();}
