import {Pill} from '/aesthetics/ui/components/components.js';
// Gallery-only presets. Transparency describes the base fill, not the composited image.
export function setupFinishes({comparison,preview,drawer,filter,say}){
 const presets={current:{name:'Current',fill:18,tint:0,rim:22,highlight:28,blur:22,saturation:180},liquid:{name:'Proposed liquid glass',fill:18,tint:16,rim:48,highlight:65,blur:22,saturation:180},clear:{name:'Clearer glass',fill:0,tint:0,rim:10,highlight:15,blur:0,saturation:180}};
 let selected='liquid';const values=structuredClone(presets),samples=new Map();
 const targets=()=>[...document.querySelectorAll('#gallery .maya-glass'),drawer,...drawer.querySelectorAll('.maya-glass'),filter,...filter.querySelectorAll('.maya-glass')].filter(e=>!e.closest('.comparison'));
 function paint(el,key){el.dataset.finish=key;const v=values[key];el.style.backgroundImage=key==='current'&&v.tint===0?'none':'';for(const [k,value] of Object.entries(v)){if(k==='name')continue;el.style.setProperty('--finish-'+k,k==='blur'?value+'px':k==='saturation'?value+'%':String(value/100));}}
 const controls=document.createElement('div');controls.className='finish-controls';controls.innerHTML='<p id="finish-status" role="status"></p><label class="clear-toggle"><input type="checkbox" id="clear-glass"> Clearer glass</label><details><summary>Adjust selected finish</summary><div class="finish-sliders"></div></details><p class="effect-note">Percentages describe separate layers, not total visual transparency. Menus keep a dark backing so text stays readable. Saturation changes the background color behind the glass: 0% is grayscale, 100% is unchanged, 180% is more vivid.</p>';comparison.after(controls);
 const sliders=[];
 for(const [key,title,min,max,unit] of [['fill','Base transparency',0,100,'%'],['tint','White tint',0,40,'%'],['highlight','Edge highlight',0,100,'%'],['blur','Blur',0,40,'px'],['saturation','Saturation',0,200,'%']]){const label=document.createElement('label'),input=document.createElement('input'),out=document.createElement('output');label.append(document.createTextNode(title));input.type='range';input.min=min;input.max=max;input.step='1';input.setAttribute('aria-label',title);input.addEventListener('input',()=>{values[selected][key]=key==='fill'?100-Number(input.value):Number(input.value);render();});label.append(input,out);controls.querySelector('.finish-sliders').append(label);sliders.push({key,input,out,unit});}
 const details=v=>`1. Base: ${100-v.fill}% transparent (${v.fill}% fill). 2. White tint: ${v.tint}%. 3. Rim: ${v.rim}%; highlight: ${v.highlight}%. 4. Blur: ${v.blur}px; saturation: ${v.saturation}%.`;
 for(const [key,preset] of Object.entries(presets)){const card=document.createElement('article');card.className='finish-sample';const title=document.createElement('button');title.type='button';title.className='finish-choice';title.textContent=preset.name;title.addEventListener('click',()=>select(key));const pill=Pill({label:'Tap to listen',purpose:'listen',onClick:()=>select(key)});const numbers=document.createElement('p');numbers.className='finish-numbers';card.append(title,pill,numbers);comparison.append(card);samples.set(key,{card,title,pill,numbers});}
 function select(key){selected=key;render();say(values[key].name+' applied to all component examples.');}
 function render(){for(const [key,{card,title,pill,numbers}] of samples){paint(pill,key);title.setAttribute('aria-pressed',String(key===selected));card.dataset.selected=String(key===selected);numbers.textContent=details(values[key]);}for(const el of targets())paint(el,selected);controls.querySelector('#clear-glass').checked=selected==='clear';controls.querySelector('#finish-status').textContent='Previewing: '+values[selected].name;for(const {key,input,out,unit} of sliders){input.value=key==='fill'?100-values[selected][key]:values[selected][key];out.value=input.value+unit;}}
 controls.querySelector('#clear-glass').addEventListener('change',e=>select(e.target.checked?'clear':'liquid'));
 render();return {settings:()=>({finish:selected,...values[selected]}),reset:()=>{Object.assign(values,structuredClone(presets));select('liquid');}};
}
