import {Pill,GlassSurface,IconButton,Drawer,FilterPopover,Metric} from '/aesthetics/ui/components/components.js';
const gallery=document.querySelector('#gallery'),feedback=document.querySelector('#feedback');
const say=s=>feedback.textContent=s;
function section(title,id,description){const s=document.createElement('section');s.id=id;s.className='preview-section';const h=document.createElement('h2');h.textContent=title;s.append(h);if(description){const p=document.createElement('p');p.textContent=description;s.append(p);}gallery.append(s);return s;}
function row(parent){const r=document.createElement('div');r.className='preview-row';parent.append(r);return r;}
const fonts=section('Fonts','fonts','Tap to listen uses Jost: 10px, light weight 300, spaced uppercase letters. Compare Arial at the same size.');
const cards=document.createElement('div');cards.className='font-grid';fonts.append(cards);
for(const [name,family,use] of [['Jost',"'Jost', sans-serif",'Current: buttons, navigation, forms and data.'],['Arial','Arial, sans-serif','Comparison only. Regular weight; not a new site font.'],['Cormorant Garamond',"'Cormorant Garamond', serif",'Current: MAYA / Mana Siyo branding and editorial titles.']]){
 const card=document.createElement('article');card.className='font-card';const h=document.createElement('h3');h.textContent=name;const p=document.createElement('p');p.textContent=use;
 card.append(h,p);if(name==='Cormorant Garamond'){const brand=document.createElement('div');brand.className='brand-sample';brand.style.fontFamily=family;brand.textContent='MAYA · MANA SIYO';card.append(brand);}else{const button=Pill({label:'Tap to listen',purpose:'listen'});button.style.fontFamily=family;if(name==='Arial')button.style.fontWeight='400';card.append(button);}
 const sample=document.createElement('div');sample.className='font-sample';sample.style.fontFamily=family;sample.textContent='MAYA 123 · Contacted · Your next appointment';card.append(sample);cards.append(card);
}
const fontNote=document.createElement('p');fontNote.id='font-status';fontNote.textContent='Loading font samples…';fonts.append(fontNote);
document.fonts.ready.then(()=>{const loaded=[...document.fonts].filter(f=>f.status==='loaded').map(f=>f.family.replaceAll('"','').replaceAll("'",''));fontNote.textContent=['Jost','Cormorant Garamond'].every(n=>loaded.includes(n))?'Jost and Cormorant loaded. Arial uses your system font.':'Web fonts unavailable or still loading; samples may show fallback fonts.';});
const technical=document.createElement('details');technical.innerHTML='<summary>Other fonts in the code</summary><p>Menlo / system monospace: technical logs, IDs and code. SF Mono and generic monospace are fallbacks, not extra brand fonts. System sans-serif is the fallback for Jost.</p><div class="mono-sample">MAYA 123 · request_id · 10:30</div>';fonts.append(technical);
const buttons=section('Buttons','buttons','Used in client MAYA, Admin and Outbound. Same small type, no oversized numbers.');
row(buttons).append(Pill({label:'Tap to listen',purpose:'listen',onClick:()=>say('Voice button example')}),IconButton({label:'Add example',onClick:()=>say('Add button example')}),Metric({label:'Contacted',value:12}));
const states=document.createElement('details');states.innerHTML='<summary>Button states</summary>';buttons.append(states);const stateRow=row(states);
for(const state of ['default','hover','focus','selected','pressed','disabled','loading']){const wrap=document.createElement('div');wrap.className='state-sample';const title=document.createElement('span');title.textContent=state;const pill=Pill({label:state==='loading'?'Listening…':'Tap to listen',purpose:'listen',disabled:['disabled','loading'].includes(state),selected:state==='selected'});if(['hover','focus','pressed'].includes(state))pill.dataset.previewState=state;if(state==='loading')pill.setAttribute('aria-busy','true');wrap.append(title,pill);stateRow.append(wrap);}
const menus=section('Menus and panels','menus','The finish changes with its job: light on buttons, quieter around data, darker over other text.');
const surfaces=document.createElement('div');surfaces.className='context-grid';menus.append(surfaces);
for(const [title,description,intensity] of [['Client actions','Tap to listen and small action buttons.','standard'],['Admin / Outbound data','Lead rows and compact totals.','quiet'],['Menus over content','Hamburger drawer and status filters.','overlay']]){const content=document.createElement('div');const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=description;content.append(h,p);surfaces.append(GlassSurface({content,intensity}));}
const drawer=Drawer({title:'Systems',content:[Metric({label:'AI today',value:'$0.12'}),GlassSurface({content:'Connection details',intensity:'quiet'})],footer:[Pill({label:'Hey MAYA',purpose:'listen'})]});let openDrawer;openDrawer=Pill({label:'Open drawer',onClick:()=>drawer.showFrom(openDrawer)});
const filter=FilterPopover({title:'Status',values:['Not contacted','Contacted','Booked'],onApply:v=>say(v.length?v.join(', '):'No statuses selected')});let openFilter;openFilter=Pill({label:'Open filter',onClick:()=>filter.showFrom(openFilter)});row(menus).append(openDrawer,openFilter);
const guide=section('Text guide','guide','What each style means and where it appears.');const table=document.createElement('table');table.className='text-guide';table.innerHTML='<thead><tr><th>Example</th><th>Used for</th><th>Style</th></tr></thead><tbody><tr><td class="brand-sample">MAYA</td><td>Brand name</td><td>Cormorant</td></tr><tr><td class="listen-sample">TAP TO LISTEN</td><td>Client voice button</td><td>Jost 10px · light</td></tr><tr><td class="body-sample">Contacted 12</td><td>Compact labels and counts</td><td>Jost 12px · numbers medium</td></tr><tr><td class="data-sample">Name · Category · Notes</td><td>Admin / Outbound tables</td><td>Jost 11px</td></tr><tr><td class="mono-sample">request_id</td><td>Technical details</td><td>System monospace</td></tr></tbody>';guide.append(table);
const glossary=document.createElement('details');glossary.innerHTML='<summary>Plain-language glossary</summary><dl><dt>Pill</dt><dd>A rounded button, like Tap to listen.</dd><dt>Glass</dt><dd>A see-through background with a soft highlight.</dd><dt>Intensity</dt><dd>How dark and blurred that background is.</dd><dt>Drawer</dt><dd>The panel opened by the hamburger menu.</dd><dt>Filter</dt><dd>The small menu for choosing which rows to show.</dd><dt>Metric</dt><dd>A label and count, such as Contacted 12.</dd><dt>Token</dt><dd>A shared setting, such as text size or padding.</dd></dl>';guide.append(glossary);
const pages=section('12 page files','pages','MAYA repository only. Affiliates is an additional view of Admin, not a separate file.');pages.innerHTML+='<ul><li><strong>1 client page:</strong> MAYA</li><li><strong>8 backend pages:</strong> Admin, Outbound, Marketing, Brief, Operations, Privacy, Terms, Verify</li><li><strong>1 embedded page:</strong> Operations engine</li><li><strong>2 preview pages:</strong> Playground, this style preview</li></ul>';
const source=await (await fetch('/aesthetics/ui/components/tokens.css')).text();
const defaults=Object.fromEntries([...source.matchAll(/(--ui-[\w-]+):\s*([^;]+);/g)].map(m=>[m[1],m[2].trim()]));
const storageKey='maya-component-gallery-tokens-v2';let saved={};try{saved=JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{}
let overrides={};
function valid(key,value){if(!value||/[;{}<>]|url\s*\(|var\s*\(/i.test(value))return false;
 if(/alpha|fill$|highlight$/.test(key))return /^0(?:\.\d+)?$|^1(?:\.0+)?$|^\.\d+$/.test(value);
 if(key==='--ui-pill-weight')return /^(300|400|500|600)$/.test(value);
 if(/(?:size|width|radius|blur|padding-[xy]|gap|space|tracking|shadow-y)$/.test(key))return /^\d+(?:\.\d+)?px$/.test(value)&&parseFloat(value)<=500;
 const property=key.endsWith('saturation')?'width':key.endsWith('duration')?'transition-duration':key.endsWith('easing')?'transition-timing-function':key.endsWith('transform')?'text-transform':key.endsWith('height')?'line-height':key.endsWith('font')?'font-family':'color';
 return CSS.supports(property,value);
}
const form=document.querySelector('#tokens');
for(const [key,value] of Object.entries(defaults)){const label=document.createElement('label'),input=document.createElement('input');label.textContent=({'--ui-font':'Interface font','--ui-pill-font-size':'Button text size','--ui-pill-padding-x':'Button side padding','--ui-pill-padding-y':'Button top/bottom padding','--ui-metric-size':'Count text size','--ui-pill-weight':'Button text weight','--ui-pill-tracking':'Letter spacing','--ui-pill-radius':'Button roundness','--ui-blur':'Background blur'})[key]||key.replace('--ui-','').replaceAll('-',' ');input.name=key;input.value=valid(key,saved[key]||'')?saved[key]:value;
 if(input.value!==value){overrides[key]=input.value;document.documentElement.style.setProperty(key,input.value);}input.addEventListener('input',()=>{const value=input.value.trim();const ok=valid(key,value);input.setAttribute('aria-invalid',String(!ok));if(!ok)return;overrides[key]=value;document.documentElement.style.setProperty(key,value);try{localStorage.setItem(storageKey,JSON.stringify(overrides));}catch{say('Preview updated; browser storage unavailable.');}});label.append(input);form.append(label);}
document.querySelector('#fallback').addEventListener('change',e=>document.body.classList.toggle('no-blur',e.target.checked));
document.querySelector('#reset').addEventListener('click',()=>{for(const key of Object.keys(defaults))document.documentElement.style.removeProperty(key);overrides={};try{localStorage.removeItem(storageKey);}catch{}for(const input of form.elements){input.value=defaults[input.name];input.removeAttribute('aria-invalid');}document.querySelector('#preview-font').value=defaults['--ui-font'];say('Defaults restored.');});
document.querySelector('#export').addEventListener('click',()=>{const css='/* MAYA preview tokens. Review before global application. */\n:root {\n'+Object.entries({...defaults,...overrides}).map(([k,v])=>'  '+k+': '+v+';').join('\n')+'\n}\n';const url=URL.createObjectURL(new Blob([css],{type:'text/css'}));const a=document.createElement('a');a.href=url;a.download='maya-tokens.css';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Tokens exported. Live pages are unchanged.');});

const choice=document.querySelector('#preview-font');choice.value=overrides['--ui-font']||defaults['--ui-font'];choice.addEventListener('change',()=>{const input=form.elements.namedItem('--ui-font');input.value=choice.value;input.dispatchEvent(new Event('input'));say(choice.selectedOptions[0].text+' selected for the examples. Font comparison cards stay fixed.');});
