import {Pill} from '/aesthetics/ui/components/components.js';
// Gallery-only presets. Transparency describes the base fill, not the composited image.
export function setupFinishes({comparison,preview,drawer,filter,say}){
 const presets={current:{name:'Current',fill:18,tint:0,rim:22,highlight:28,blur:22,saturation:180},liquid:{name:'Liquid',fill:18,tint:16,rim:48,highlight:65,blur:22,saturation:180},clear:{name:'Clear',fill:0,tint:0,rim:10,highlight:15,blur:0,saturation:180}};
 let selected='current';const values=structuredClone(presets),samples=new Map();
 const targets=()=>[...document.querySelectorAll('#gallery .maya-glass,#save'),drawer,...drawer.querySelectorAll('.maya-glass'),filter,...filter.querySelectorAll('.maya-glass')].filter(e=>!e.closest('.comparison'));
 function paint(el,key){el.dataset.finish=key;const v=values[key];el.style.backgroundImage=key==='current'&&v.tint===0?'none':'';for(const [k,value] of Object.entries(v)){if(k==='name')continue;el.style.setProperty('--finish-'+k,k==='blur'?value+'px':k==='saturation'?value+'%':String(value/100));}}
 const controls=document.createElement('div');controls.className='finish-controls';controls.innerHTML='<p id="finish-status" role="status"></p><details><summary>Edit glass</summary><div class="finish-sliders"></div></details>';comparison.after(controls);
 const sliders=[];
 for(const [key,title,min,max,unit] of [['fill','Transparency',0,100,'%'],['tint','Tint',0,40,'%'],['rim','Rim',0,100,'%'],['highlight','Highlight',0,100,'%'],['blur','Blur',0,40,'px'],['saturation','Saturation',0,200,'%']]){const label=document.createElement('label'),input=document.createElement('input'),out=document.createElement('output');label.append(document.createTextNode(title));input.type='range';input.min=min;input.max=max;input.step='1';input.setAttribute('aria-label',title);input.addEventListener('input',()=>{values[selected][key]=key==='fill'?100-Number(input.value):Number(input.value);render();});label.append(input,out);controls.querySelector('.finish-sliders').append(label);sliders.push({key,input,out,unit});}

 for(const [key,preset] of Object.entries(presets)){const card=document.createElement('article');card.className='finish-sample';const title=document.createElement('button');title.type='button';title.className='finish-choice';title.textContent=preset.name;title.addEventListener('click',()=>select(key));const pill=Pill({label:'Tap to listen',purpose:'listen',onClick:()=>select(key)});const numbers=document.createElement('p');numbers.className='finish-numbers';card.append(title,pill,numbers);comparison.append(card);samples.set(key,{card,title,pill,numbers});}
 function select(key){selected=key;render();}
 function render(){for(const [key,{card,title,pill,numbers}] of samples){paint(pill,key);title.setAttribute('aria-pressed',String(key===selected));title.textContent=values[key].name+(key===selected?' ✓':'');card.dataset.selected=String(key===selected);numbers.textContent='';}for(const el of targets())paint(el,selected);controls.querySelector('#finish-status').textContent='Previewing: '+values[selected].name;for(const {key,input,out,unit} of sliders){input.value=key==='fill'?100-values[selected][key]:values[selected][key];out.value=input.value+unit;}}
 new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['style']});
 render();return {settings:()=>({finish:selected,...values[selected]}),set:v=>{if(v&&values[v.finish]){for(const key of ['fill','tint','rim','highlight','blur','saturation'])if(Number.isInteger(v[key]))values[v.finish][key]=v[key];select(v.finish);}},reset:()=>{Object.assign(values,structuredClone(presets));select('current');}};
}
