import {fields,borders} from './surface-editors.js';
import {Pill} from '/aesthetics/ui/components/components.js';
// Gallery-only presets. Transparency describes the base fill, not the composited image.
export function setupFinishes({comparison,preview,drawer,say}){
 const presets={current:{name:'Current',borderColor:'white',fill:18,tint:0,rim:22,highlight:28,blur:22,saturation:180},liquid:{name:'Liquid',borderColor:'white',fill:18,tint:16,rim:48,highlight:65,blur:22,saturation:180},clear:{name:'Clear',borderColor:'white',fill:0,tint:0,rim:10,highlight:15,blur:0,saturation:180}};
 let selected='current';const values=structuredClone(presets),samples=new Map();
 const targets=()=>[...document.querySelectorAll('#gallery .maya-glass,#save'),drawer,...drawer.querySelectorAll('.maya-glass')].filter(e=>!e.closest('.comparison'));
 function paint(el,key){el.style.setProperty('--finish-border-rgb',values[key].borderColor==='black'?'0 0 0':values[key].borderColor==='gray'?'170 181 196':'255 255 255');el.dataset.finish=key;const v=values[key];el.style.backgroundImage=key==='current'&&v.tint===0?'none':'';for(const [k,value] of Object.entries(v)){if(k==='name'||k==='borderColor')continue;el.style.setProperty('--finish-'+k,k==='blur'?value+'px':k==='saturation'?value+'%':String(value/100));}}
 const controls=document.createElement('div');controls.className='finish-controls';controls.innerHTML='<p id="finish-status" role="status"></p><details class="type-editor"><summary>Edit glass</summary><div class="type-editor-fields"></div></details>';comparison.after(controls);
 const formValues={...values[selected]};fields(controls.querySelector('.type-editor-fields'),formValues,[['fill','Opacity',{max:100}],['rim','Border',{max:100}],['borderColor','Border color',borders],['tint','Tint',{max:40}],['highlight','Highlight',{max:100}],['blur','Blur',{max:40}],['saturation','Saturation',{max:200}]],()=>{Object.assign(values[selected],formValues);render();});
 for(const [key,preset] of Object.entries(presets)){const card=document.createElement('article');card.className='finish-sample';const title=document.createElement('button');title.type='button';title.className='finish-choice';title.textContent=preset.name;title.addEventListener('click',()=>select(key));const pill=Pill({label:'Tap to listen',purpose:'listen',onClick:()=>select(key)});const numbers=document.createElement('p');numbers.className='finish-numbers';card.append(title,pill,numbers);comparison.append(card);samples.set(key,{card,title,pill,numbers});}
 function select(key){selected=key;render();}
 function render(){Object.assign(formValues,values[selected]);for(const input of controls.querySelectorAll('[data-field]'))if(Object.hasOwn(formValues,input.dataset.field))input.value=formValues[input.dataset.field];for(const [key,{card,title,pill,numbers}] of samples){paint(pill,key);title.setAttribute('aria-pressed',String(key===selected));title.textContent=values[key].name+(key===selected?' ✓':'');card.dataset.selected=String(key===selected);numbers.textContent='';}for(const el of targets())paint(el,selected);controls.querySelector('#finish-status').textContent='Previewing: '+values[selected].name;}

 new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['style']});
 render();return {settings:()=>({finish:selected,...values[selected]}),set:v=>{if(v&&values[v.finish]){for(const key of ['fill','tint','rim','highlight','blur','saturation'])if(Number.isInteger(v[key]))values[v.finish][key]=v[key];values[v.finish].borderColor=['black','gray','white'].includes(v.borderColor)?v.borderColor:'white';select(v.finish);}},reset:()=>{Object.assign(values,structuredClone(presets));select('current');}};
}
