import {setupPresentation} from './presentation-controls.js';
import {formatTools,formatIcon,formatIcons} from './format-tools.js';
import {addRestore,highlightPadding} from './restore-controls.js';
import {setupSurfaceEditors,setupDismissal,fields,backgrounds,borders} from './surface-editors.js';
import {setupOverlay} from './overlay.js';
import {setupFinishes} from './finishes.js';
import {Pill,IconButton,Drawer,Metric} from '/aesthetics/ui/components/components.js';
document.querySelector('#admin-back').addEventListener('click',e=>{if(window.parent!==window){e.preventDefault();window.parent.postMessage({type:'maya-design-close'},location.origin);}});
const gallery=document.querySelector('#gallery'),feedback=document.querySelector('#feedback');
const say=s=>{feedback.textContent=s;feedback.classList.toggle('save-error',/failed|required|must|Sign in|error/i.test(s));};
const storedDesign=await window.MayaTypographyControls.ready;
function section(title,id){const s=document.createElement('section');s.id=id;s.className='preview-section';const h=document.createElement('h2');h.textContent=title;h.className='gallery-section-title';s.append(h);gallery.append(s);return s;}
function row(parent){const r=document.createElement('div');r.className='preview-row';parent.append(r);return r;}
function heading(parent,title){const h=document.createElement('h2');h.textContent=title;h.className='gallery-section-title';parent.append(h);}
const preview=section('Glass, Panels and Tables','pill-preview');
const buttons=document.createElement('div');buttons.id='buttons';preview.append(buttons);heading(buttons,'Pills');
const comparison=document.createElement('div');comparison.className='comparison';buttons.append(comparison);
function openGlassSettings(event){event?.stopPropagation();const edit=document.querySelector('.finish-controls details');if(edit){edit.open=true;edit.querySelector('input')?.focus();}}
const contextActions=row(buttons);contextActions.append(Pill({label:'Tap to listen',purpose:'listen',onClick:openGlassSettings}));
const iconRow=row(buttons);iconRow.classList.add('icon-row');
for(const [label,icon] of [['Save','Save'],['Add','+'],['Decrease font size','−'],['Close','×'],['Refresh','↻'],['Bold','B'],['Italic','I']])iconRow.append(IconButton({label,icon,onClick:event=>openIconSettings(event)}));
const activeIcons=new Set(['Menu','Search','Dropdown','Phone','Share','Email','Microphone','Copy','Favorite','Edit','Send','Settings']);
for(const [label,path] of [['Menu','M4 6h16M4 12h16M4 18h16'],['Search','M10 4a6 6 0 1 0 0 12a6 6 0 0 0 0-12M15 15l5 5'],['Dropdown','M6 9l6 6 6-6'],['Phone','M6 3h4l2 6-3 2a16 16 0 0 0 4 4l2-3 6 2v4c0 5-18-1-18-12z'],['Share','M12 16V3m-4 4 4-4 4 4M5 12v8h14v-8'],['Email','M3 5h18v14H3zM3 5l9 8 9-8'],['Microphone','M9 4a3 3 0 0 1 6 0v8a3 3 0 0 1-6 0zM6 10v2a6 6 0 0 0 12 0v-2M12 18v4M8 22h8'],['Copy','M8 8h12v13H8zM4 16V3h12'],['Download','M12 3v12M7 10l5 5 5-5M4 17v4h16v-4'],['Favorite','M12 20S2 14 2 8a5 5 0 0 1 10-3 5 5 0 0 1 10 3c0 6-10 12-10 12z'],['Expand','M3 9V3h6M15 3h6v6M21 15v6h-6M9 21H3v-6'],['Edit','M4 16l12-12 4 4L8 20H4zM14 6l4 4'],['Upload','M12 16V3M7 8l5-5 5 5M4 17v4h16v-4'],['Send','M3 3l18 9-18 9 3-9zM6 12h15'],['Invoice','M6 3h12v18l-3-2-3 2-3-2-3 2zM9 7h6M9 11h6M9 15h4'],['History','M3 10a9 9 0 1 1 2 8M3 4v6h6M12 7v5l3 2'],['Help','M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4M12 18v1'],['Stop','M5 5h14v14H5z'],['Settings','m9.5 3-.5 2-2 1-2-.5-2 3.5L4.5 11v2L3 15l2 3.5 2-.5 2 1 .5 2h5l.5-2 2-1 2 .5 2-3.5-1.5-2v-2L21 9l-2-3.5-2 .5-2-1-.5-2z M15 12a3 3 0 1 0-6 0 3 3 0 1 0 6 0']].filter(([label])=>activeIcons.has(label))){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');const line=document.createElementNS(svg.namespaceURI,'path');line.setAttribute('d',path);svg.append(line);iconRow.append(IconButton({label,icon:svg,onClick:event=>openIconSettings(event)}));}
for(const label of Object.keys(formatIcons))iconRow.append(IconButton({label,icon:formatIcon(label),onClick:event=>openIconSettings(event)}));
const controlSizes={iconColor:storedDesign.iconColor,iconOpacity:storedDesign.iconOpacity,iconStroke:storedDesign.iconStroke,iconSize:storedDesign.iconSize,dropdownHeight:storedDesign.dropdownHeight,iconPillGap:storedDesign.iconPillGap,iconTextGap:storedDesign.iconTextGap};
const sizeEdit=document.createElement('details');sizeEdit.className='type-editor control-size-editor';sizeEdit.innerHTML='<summary>Icons and dropdown</summary><div class="type-editor-fields"></div>';buttons.append(sizeEdit);
let presentation;
const sizeRender=()=>{presentation?.render();document.documentElement.style.setProperty('--maya-icon-pill-gap',controlSizes.iconPillGap+'px');document.documentElement.style.setProperty('--maya-icon-text-gap',controlSizes.iconTextGap+'px');document.documentElement.style.setProperty('--preview-control-height',controlSizes.iconSize+'px');document.documentElement.style.setProperty('--maya-control-icon-size',controlSizes.iconSize+'px');document.documentElement.style.setProperty('--maya-control-dropdown-height',controlSizes.dropdownHeight+'px');};
addRestore(sizeEdit,{label:'icons and dropdown',read:()=>controlSizes,write:v=>{Object.assign(controlSizes,v);for(const input of sizeEdit.querySelectorAll('[data-field]'))input.value=controlSizes[input.dataset.field];sizeRender();}});
fields(sizeEdit.lastChild,controlSizes,[['iconColor','Icon color',{type:'color'}],['iconOpacity','Color strength',{min:0,max:100}],['iconStroke','Stroke width',{min:1,max:3}],['iconSize','Icon size',{min:24,max:48}],['dropdownHeight','Dropdown height',{min:24,max:48}],['iconPillGap','Inside pill gap',{min:0,max:32}],['iconTextGap','Beside text gap',{min:0,max:32}]],sizeRender);
// Live icon material and spacing examples, wired to the same saved controls.
const iconSpacing=row(buttons);iconSpacing.classList.add('icon-spacing-preview');
const openIconSettings=event=>{event?.stopPropagation();sizeEdit.open=true;sizeEdit.querySelector('input')?.focus();};
const gear=()=>{const svg=iconRow.querySelector('[aria-label="Settings"] svg').cloneNode(true);svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.6');return svg;};
const inside=Pill({label:'Settings',onClick:openIconSettings});inside.id='icon-pill-preview';const insideText=document.createElement('span');insideText.textContent='Settings';inside.replaceChildren(insideText,gear());
const outside=document.createElement('span');outside.className='maya-icon-row';outside.id='icon-text-preview';const title=document.createElement('span');title.textContent='Status';title.dataset.previewCategory='P1';const bare=document.createElement('button');bare.className='maya-inline-icon';bare.type='button';bare.setAttribute('aria-label','Edit beside-text icon spacing');bare.append(iconRow.querySelector('[aria-label="Dropdown"] svg').cloneNode(true));bare.onclick=openIconSettings;outside.append(title,bare);iconSpacing.append(inside,outside);
const dropdown=document.createElement('select');dropdown.className='dropdown-preview';dropdown.setAttribute('aria-label','Dropdown preview');dropdown.innerHTML='<option>Signature</option><option>Ceremonial</option><option>Suit</option><option>Help me decide</option>';dropdown.onchange=()=>say(dropdown.value+' preview');row(buttons).append(dropdown);sizeRender();
const colors=row(buttons);colors.id='pill-colors';
presentation=setupPresentation({buttons,preview,colors,design:storedDesign,controlSizes});
const states=document.createElement('details');states.innerHTML='<summary>States</summary>';buttons.append(states);const stateRow=row(states);
for(const state of ['default','hover','focus','selected','pressed','disabled','loading']){const wrap=document.createElement('div');wrap.className='state-sample';const label=document.createElement('span');label.textContent=state;const pill=Pill({label:'Tap to listen',purpose:'listen',disabled:['disabled','loading'].includes(state),selected:state==='selected',onClick:openGlassSettings});if(['hover','focus','pressed'].includes(state))pill.dataset.previewState=state;if(state==='loading')pill.setAttribute('aria-busy','true');wrap.append(label,pill);stateRow.append(wrap);}
const divider=document.createElement('hr');divider.className='visual-divider';preview.append(divider);
const panels=document.createElement('div');panels.id='panels';preview.append(panels);heading(panels,'Panels');
const surfaces=document.createElement('div');surfaces.className='context-grid';const outer=surfaces;outer.classList.add('panel-preview');panels.append(outer);
for(const title of ['Lead Station','Campaign details']){const h=document.createElement('h3');h.textContent=title;h.dataset.previewCategory='H3';const metric=Metric({label:'Contacts',value:12});const inner=document.createElement('div');inner.className='inner-panel';inner.append(h,metric);surfaces.append(inner);}
const drawer=Drawer({title:'Systems',content:[Pill({label:'Aesthetic Control',onClick:()=>drawer.close()})]});
let openDrawer;openDrawer=Pill({label:'Drawer',onClick:()=>drawer.showFrom(openDrawer)});row(panels).append(openDrawer);
const guide=document.createElement('div');guide.id='table-preview';guide.tabIndex=0;guide.setAttribute('role','region');guide.setAttribute('aria-label','Lead Station table preview');panels.append(guide);
const table=document.createElement('table');table.className='text-guide';table.innerHTML='<thead><tr><th data-col="name">Full name</th><th data-col="contact">Contact</th><th data-col="stage">Status</th><th data-col="note">Latest Notes</th></tr></thead><tbody></tbody>';guide.append(table);
for(const [name,phone,date,status,color,note] of [['Angela','+1 415 555 0101','Oct 1','Not contacted','#b5bdc8','Wedding, gala, or ceremony'],['Mary','+1 415 555 0102','Sep 4','Completed','#4ade80','A custom suit with a tailored fit']]){
 const tr=document.createElement('tr');tr.innerHTML='<td data-col="name" class="lead-col-first"><button class="lead-open"><span class="lead-identity" data-preview-category="H4">'+name+'</span><time class="lead-signup" data-preview-category="H5">'+date+'</time></button></td><td data-col="contact">'+phone+'</td><td data-col="stage"><span class="status-pill lead-status" data-status="'+(status==='Completed'?'completed':'new')+'" style="--status-color:'+color+'">'+status+'</span></td><td data-col="note"><div class="lead-note-vp"><span>'+note+'</span></div></td>';table.tBodies[0].append(tr);
}
const surfacesEditor=setupSurfaceEditors({panels,guide,design:storedDesign});
const fonts=section('Typography','fonts'),hierarchy=document.createElement('div');hierarchy.className='type-hierarchy';fonts.append(hierarchy);
const typeSettings=structuredClone(storedDesign.type||window.MayaTypographyControls.defaults.type);
const usage=await fetch('/aesthetics/aesthetic-control/typography-usage.json').then(r=>r.json()).catch(()=>({categories:{}}));
const editorSettings={...window.MayaTypographyControls.defaults.editor,...storedDesign.editor};
function renderEditor(){window.MayaTypographyControls.previewEditor(editorSettings);}
renderEditor();
const roles=[['H0','signin','Maya','Sign-in'],['H1','brand','Maya','Brand'],['H2','drawer','Systems','Drawer'],['H3','subheadline','Campaign details','Lead Station / campaign details'],['H4','dashboard','Angela · 12','Lead names / dashboard numbers'],['H5','leaddate','Oct 4','Lead date'],['P1','paragraph','Your next appointment.','Body / tables'],['P2','label','Contacts 12','Labels'],['P3','field','Name','Pills / fields / captions']];
for(const [category,key,text,where] of roles){
 typeSettings[category].align||='center';typeSettings[category].vertical||='middle';
 const group=document.createElement('section');group.className='type-group';group.dataset.category=category;
 const head=document.createElement('div');head.className='type-group-head';const title=document.createElement('h3');title.className='type-category';title.textContent=category+' ('+(usage.categories?.[category]?.count??'?')+')';title.title='Authored uses across MAYA';head.append(title);group.append(head);hierarchy.append(group);
 const edit=document.createElement('details');edit.className='type-editor';edit.innerHTML='<summary aria-label="Edit '+category+'">Edit</summary><div class="type-editor-fields"><label>Font <select data-field="font"><option value="jost">Jost</option><option value="cormorant">Cormorant</option></select></label><label>Case <select data-field="case"><option value="none">Normal</option><option value="uppercase">ALL CAPS</option></select></label><label>Size <input type="number" min="8" max="32" step="2" data-field="size"></label><label>Weight <select data-field="weight"><option>200</option><option>250</option><option>300</option><option>350</option><option>400</option><option>450</option><option>500</option></select></label><label>Style <select data-field="style"><option value="normal">Normal</option><option value="italic">Italic</option></select></label><label>Color <select data-field="color"><option value="white">White</option><option value="gray">Gray</option></select></label><label>Alignment <select data-field="align"><option value="left">Left</option><option value="center">Centered</option><option value="right">Right</option></select></label><label>Vertical <select data-field="vertical"><option value="top">Top</option><option value="middle">Middle</option><option value="bottom">Bottom</option></select></label></div>';head.append(edit);if(category==='H0'){const size=edit.querySelector('[data-field="size"]');size.min='24';size.max='160';}
 const spec=document.createElement('span');spec.className='category-setting';head.append(spec);
 const item=document.createElement('article');item.className='type-row';item.dataset.type=key;const example=document.createElement('div');example.className='type-example';example.textContent=text;const meta=document.createElement('small');meta.className='type-setting';meta.textContent=where;const locations=usage.categories?.[category]?.locations||[];const renderedPages=page=>page==='backend/outbound.js'?['backend/outbound.html']:page==='aesthetics/ui/owner-crm.js'?['backend/status.html']:page==='aesthetics/ui/ai-meter.js'?['backend/status.html','backend/outbound.html']:[page];const pages=[...new Set(locations.flatMap(x=>renderedPages(x.page)))];
 const route=page=>({'frontend/index.html':'/','backend/status.html':'/status.html','playground/index.html':'/playground.html','aesthetics/operations/index.html':'/aesthetics/operations/'}[page]||'/'+page.split('/').at(-1));
 meta.append(document.createTextNode(' — '));pages.forEach((page,i)=>{if(i)meta.append(document.createTextNode(', '));const link=document.createElement('a');link.href=route(page);link.textContent=page==='aesthetics/operations/index.html'?'Components':page==='frontend/index.html'?'App':page==='playground/index.html'?'Playground':page.split('/').at(-1).replace('.html','');link.title=page;meta.append(link);});
 const evidence=document.createElement('details');evidence.className='role-locations';const evidenceTitle=document.createElement('summary');evidenceTitle.textContent=locations.length+' locations';evidence.append(evidenceTitle);
 for(const loc of locations){const link=document.createElement('a');link.href=route(renderedPages(loc.page)[0])+(loc.id?'#'+loc.id:'');link.title=loc.snippet||'';link.textContent=loc.page+':'+loc.line+' · '+(loc.id?'#'+loc.id:loc.class?'.'+loc.class.split(' ').join('.'):'<'+loc.tag+'>');const excerpt=(/^<[^>]*>([^<]+)/.exec(loc.snippet||'')?.[1]||'').trim().slice(0,60);if(excerpt)link.append(document.createTextNode(' — '+excerpt));evidence.append(link);}
 meta.append(evidence);item.append(example,meta);group.append(item);
 function render(){group.formatSync?.();const t=typeSettings[category],family=t.font==='cormorant'?"'Cormorant Garamond', serif":"'Jost', sans-serif";spec.textContent=t.size+'px · '+t.weight;for(const e of [example,...document.querySelectorAll('[data-preview-category="'+category+'"]')])for(const [property,value] of [['font-family',family],['text-transform',t.case],['font-size',category==='H0'?'clamp(24px,18vw,'+t.size+'px)':t.size+'px'],['font-weight',t.weight],['font-style',t.style||'normal'],['text-align',t.align],['align-self',t.vertical==='top'?'start':t.vertical==='bottom'?'end':'center'],['color',t.color==='white'?'rgb(255 255 255)':'rgb(170 181 196)']])if(!(['color','font-weight'].includes(property)&&e.classList.contains('status-pill'))){if(property==='align-self'&&e.closest('.maya-icon-row'))e.style.removeProperty(property);else e.style.setProperty(property,value,'important');}}
 for(const field of edit.querySelectorAll('[data-field]')){field.value=String(typeSettings[category][field.dataset.field]);field.addEventListener('input',()=>{const key=field.dataset.field,v=['size','weight'].includes(key)?Number(field.value):field.value;if(key==='size'&&(!Number.isInteger(v)||v<(category==='H0'?24:8)||v>(category==='H0'?160:32)||v%2))return;typeSettings[category][key]=v;render();});}
 group.formatSync=formatTools(edit.querySelector('.type-editor-fields'),()=>typeSettings[category]);addRestore(edit,{label:category,read:()=>typeSettings[category],write:v=>{Object.assign(typeSettings[category],v);for(const field of edit.querySelectorAll('[data-field]'))field.value=typeSettings[category][field.dataset.field];render();}});group.renderType=render;render();
}
function collapsible(section){const h=section.querySelector(':scope > h2'),details=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('div');details.className='review-fold';details.open=true;summary.append(h);body.className='review-fold-body';body.append(...section.childNodes);details.append(summary,body);section.append(details);}
collapsible(preview);collapsible(fonts);
for(const link of document.querySelectorAll('.gallery-header nav a'))link.addEventListener('click',()=>{const fold=document.querySelector(link.getAttribute('href')+' > .review-fold');if(fold)fold.open=true;});
const finishes=setupFinishes({comparison,preview,drawer,say});
const overlay=setupOverlay(comparison);const panelToolbar=document.createElement('div');panelToolbar.className='panel-editors';
const outerControl=document.createElement('div');outerControl.className='surface-edit-row';outerControl.append(document.createTextNode('Outer panel'),document.querySelector('.overlay-controls'));
panelToolbar.append(outerControl,...panels.querySelectorAll(':scope > .surface-edit-row'));outer.before(panelToolbar);
const panelUsage=document.createElement('p');panelUsage.className='panel-usage';panelUsage.append(document.createTextNode('Inner panels — '));for(const [label,url] of [['Aesthetic previews','#panels'],['Outbound cards and detail','/outbound.html'],['Operation Room cards','/operations.html'],['Pattern Operations cards','/aesthetics/operations/index.html']]){const link=document.createElement('a');link.textContent=label;link.href=url;panelUsage.append(link,document.createTextNode(', '));}panelUsage.append(document.createTextNode('tables use Table settings.'));panelToolbar.after(panelUsage);
const popupEdit=document.createElement('details');popupEdit.className='type-editor popup-editor';popupEdit.innerHTML='<summary>Edit dropdown</summary><div class="type-editor-fields"></div>';const popupRow=row(buttons);popupRow.append(popupEdit);fields(popupEdit.lastChild,editorSettings,[['background','Background',backgrounds],['fill','Opacity',{max:100}],['rim','Border',{max:100}],['borderColor','Border color',borders],['radius','Corners',{max:24}],['paddingX','Padding X',{max:40}],['paddingY','Padding Y',{max:40}]],renderEditor);highlightPadding(popupEdit,()=>[popupEdit.querySelector('.type-editor-fields')],()=>({x:editorSettings.paddingX,y:editorSettings.paddingY}));addRestore(popupEdit,{label:'dropdown',read:()=>editorSettings,write:v=>{Object.assign(editorSettings,v);for(const input of popupEdit.querySelectorAll('[data-field]'))input.value=editorSettings[input.dataset.field];renderEditor();}});
const form=document.createElement('div');form.id='tokens';buttons.querySelector('.finish-controls .type-editor-fields').append(form);
if(storedDesign?.glass)finishes.set({finish:storedDesign.finish,...storedDesign.glass});if(storedDesign?.overlay)overlay.set(storedDesign.overlay);
addRestore(document.querySelector('.overlay-controls'),{label:'outer panel',read:overlay.settings,write:overlay.set});



const regularPill={...storedDesign.regularPill};
const regularEdit=document.createElement('details');regularEdit.className='type-editor regular-pill-editor';regularEdit.innerHTML='<summary>Edit regular pill</summary><div class="type-editor-fields"></div>';
const regularSection=document.createElement('section');regularSection.className='pill-family';regularSection.dataset.pillFamily='regular';
const regularTitle=document.createElement('h3');regularTitle.dataset.mayaType='H3';regularTitle.dataset.previewCategory='H3';regularTitle.textContent='Pill 2 · Regular';const regularControls=document.createElement('div');regularControls.className='surface-edit-row';regularControls.append(regularEdit);regularSection.append(regularTitle,regularControls);document.querySelector('.finish-controls').after(regularSection);
const regularSample=Pill({label:'Regular pill',onClick:event=>{event.stopPropagation();regularEdit.open=true;regularEdit.querySelector('input').focus();}});regularSample.dataset.mayaPill='regular';regularSample.classList.remove('maya-glass');regularSection.prepend(regularSample);
function renderRegular(){MayaTypographyControls.previewPills({...storedDesign,regularPill,pillX:pillPadding.paddingX,pillY:pillPadding.paddingY});}
fields(regularEdit.lastChild,regularPill,[['background','Background',backgrounds],['fill','Opacity',{max:100}],['rim','Border',{max:100}],['borderColor','Border color',borders],['paddingX','Padding X',{min:4,max:32}],['paddingY','Padding Y',{min:2,max:16}]],renderRegular);
addRestore(regularEdit,{label:'regular pill',read:()=>regularPill,write:v=>{Object.assign(regularPill,v);for(const input of regularEdit.querySelectorAll('[data-field]'))input.value=regularPill[input.dataset.field];renderRegular();}});
highlightPadding(regularEdit,()=>[regularSample,...document.querySelectorAll('.type-editor>summary')],()=>({x:regularPill.paddingX,y:regularPill.paddingY}));
for(const [kind,host] of [['glass',document.querySelector('.finish-controls')],['regular',regularSection]]){
 const usage=document.createElement('details');usage.className='pill-usage';const summary=document.createElement('summary');summary.dataset.mayaType='P3';summary.textContent='Where this pill is used';usage.append(summary);
 for(const [label,url,uses] of MayaPillControls.usage[kind]){const line=document.createElement('p');line.dataset.mayaType='P1';const link=document.createElement('a');link.href=url;link.textContent=label;line.append(link,document.createTextNode(' — '+uses));usage.append(line);}host.append(usage);
}
const pillPadding={paddingX:storedDesign.pillX,paddingY:storedDesign.pillY};
function renderPillPadding(){MayaTypographyControls.previewPills({...storedDesign,regularPill,pillX:pillPadding.paddingX,pillY:pillPadding.paddingY});}
fields(form,pillPadding,[['paddingX','Padding X',{min:4,max:32}],['paddingY','Padding Y',{min:2,max:16}]],renderPillPadding);renderPillPadding();
document.querySelector('#save').addEventListener('click',async()=>{
 const sizes=['H1','H2','H3','H4','P1','P2','P3'].map(k=>typeSettings[k].size);
 if(sizes.slice(0,4).some((n,i)=>i&&n>=sizes[i-1])||sizes.slice(4).some((n,i)=>i&&n>sizes[i+3])){say('Headlines must descend in size; paragraphs must not grow down the list.');return;}
 const pillX=pillPadding.paddingX,pillY=pillPadding.paddingY;
 if(!Number.isInteger(pillX)||pillX<4||pillX>32||!Number.isInteger(pillY)||pillY<2||pillY>16){say('Pill padding must stay within 4–32px sideways and 2–16px vertically.');return;}
 const glass=finishes.settings();const value={...controlSizes,...presentation.settings(),typeVersion:2,type:typeSettings,regularPill,finish:glass.finish,glass:Object.fromEntries(['fill','tint','rim','highlight','blur','saturation','borderColor'].map(k=>[k,glass[k]])),overlay:overlay.settings(),editor:editorSettings,...surfacesEditor.settings(),pillX:pillPadding.paddingX,pillY:pillPadding.paddingY};
 const button=document.querySelector('#save'),editors=[gallery,document.querySelector('#cell-format-toolbar')].filter(Boolean);
 const previousInert=editors.map(el=>el.inert);button.disabled=true;editors.forEach(el=>el.inert=true);say('Saving…');
 try{say(await window.MayaTypographyControls.save(structuredClone(value)));document.dispatchEvent(new Event('maya-gallery-saved'));}
 catch(e){say(e.message||'Save failed.');}
 finally{editors.forEach((el,i)=>el.inert=previousInert[i]);button.disabled=false;}
});

addRestore(document.querySelector('.finish-controls details'),{label:'glass',read:()=>({...finishes.settings(),pillX:pillPadding.paddingX,pillY:pillPadding.paddingY}),write:v=>{finishes.set(v);Object.assign(pillPadding,{paddingX:v.pillX,paddingY:v.pillY});for(const input of form.querySelectorAll('[data-field]'))input.value=pillPadding[input.dataset.field];renderPillPadding();}});
highlightPadding(document.querySelector('.finish-controls details'),()=>[...document.querySelectorAll('#gallery .maya-pill:not([data-maya-pill=regular]),#gallery .maya-icon-button,#save')],()=>({x:pillPadding.paddingX,y:pillPadding.paddingY}));
setupDismissal();

for(const pill of document.querySelectorAll('.maya-pill'))pill.dataset.previewCategory='P3';for(const label of document.querySelectorAll('.maya-metric-label,.maya-metric-value'))label.dataset.previewCategory='P2';for(const group of hierarchy.querySelectorAll('.type-group'))group.renderType();
