// Review containers are a separate material layer from the action pills.
export function setupOverlay(comparison){
 const defaults={fill:18,rim:22,blur:22,saturation:180,paddingX:16,paddingY:16},values={...defaults};let enabled=true;
 const panel=document.createElement('details');panel.className='overlay-controls';panel.innerHTML='<summary>Edit panels</summary><label><input id="overlay-enabled" type="checkbox" checked> Glass</label><div class="finish-sliders"></div><button type="button" class="padding-debug" data-padding-debug="outer" aria-pressed="false">Show padding</button>';
 comparison.parentElement.querySelector('.finish-controls').after(panel);
 const fields=[];
 for(const [key,label,max,unit] of [['fill','Fill',100,'%'],['rim','Border',100,'%'],['blur','Blur',40,'px'],['saturation','Saturation',200,'%'],['paddingX','Padding X',40,'px'],['paddingY','Padding Y',40,'px']]){
  const row=document.createElement('label'),input=document.createElement('input'),output=document.createElement('output');row.append(document.createTextNode(label));input.type='range';input.min=0;input.max=max;input.setAttribute('aria-label',label);input.addEventListener('input',()=>{values[key]=Number(input.value);render();});row.append(input,output);panel.querySelector('.finish-sliders').append(row);fields.push({key,input,output,unit});
 }
 function render(){const root=document.documentElement;for(const [key,value] of Object.entries(values))root.style.setProperty('--review-panel-'+key,['blur','paddingX','paddingY'].includes(key)?value+'px':key==='saturation'?value+'%':String(enabled?value/100:0));root.style.setProperty('--maya-frost',enabled?`blur(${values.blur}px) saturate(${values.saturation}%)`:'none');root.style.setProperty('--review-panel-filter',enabled?`blur(${values.blur}px) saturate(${values.saturation}%)`:'none');for(const f of fields){f.input.value=values[f.key];f.output.value=values[f.key]+f.unit;}panel.querySelector('input[type=checkbox]').checked=enabled;for(const e of document.querySelectorAll('#panels .maya-surface')){e.style.setProperty('--padding-debug-x',values.paddingX+'px');e.style.setProperty('--padding-debug-y',values.paddingY+'px');}}
 panel.querySelector('[data-padding-debug]').onclick=e=>{const on=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'Hide padding':'Show padding';document.querySelectorAll('#panels .maya-surface').forEach(el=>el.classList.toggle('show-padding',on));};
 panel.querySelector('input[type=checkbox]').addEventListener('change',e=>{enabled=e.target.checked;render();});render();return {settings:()=>({enabled,...values}),set:v=>{for(const key of Object.keys(values))if(Number.isInteger(v?.[key]))values[key]=v[key];enabled=v?.enabled!==false;render();},reset:()=>{Object.assign(values,defaults);enabled=true;render();}};
}
