// Owner setup uses the Admin session; the browser never supplies a trusted phone number.
class OwnerCRM extends HTMLElement{
 connectedCallback(){if(this.ready)return;this.ready=true;this.innerHTML='<h3>Owner tools</h3><p class="small" role="status">Checking owner tools…</p><button type="button" class="enable-owner">Enable my text commands</button><button type="button" class="test-gemini">Test Gemini</button><a class="drawer-link" href="/outbound.html">Connect Gmail in Outbound</a><button type="button" class="gmail-review">Review Gmail leads</button><div class="gmail-candidates"></div>';this.querySelector('.enable-owner').onclick=()=>this.enable();this.querySelector('.test-gemini').onclick=()=>this.testGemini();this.querySelector('.gmail-review').onclick=()=>this.review();this.onStorage=e=>{if(e.key==='maya_admin_tok'||e.key===null){this.querySelector('.gmail-candidates').replaceChildren();this.load();}};window.addEventListener('storage',this.onStorage);this.load();}
 disconnectedCallback(){window.removeEventListener('storage',this.onStorage);this.ready=false;}
 async request(path,method='GET',body){const token=localStorage.getItem('maya_admin_tok');if(!token)throw Error('Sign in to use owner tools.');const r=await fetch('/api/admin/owner-crm'+path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json();if(token!==localStorage.getItem('maya_admin_tok'))throw Error('Account changed. Reload owner tools.');if(!r.ok)throw Error(j.error||'Owner tools unavailable.');return j;}
 async load(){try{const j=await this.request('');this.querySelector('.enable-owner').hidden=!!j.enabled;this.querySelector('p').textContent=(j.enabled?'Text commands enabled':'Text commands off')+' · your number ending '+j.numberEnding+'. '+j.mailboxes.length+' Gmail mailboxes connected.'+(j.gmailReady?'':' Gmail needs server setup.');}catch(e){this.querySelector('p').textContent=e.message;}}
 async testGemini(){const b=this.querySelector('.test-gemini');b.disabled=true;this.querySelector('p').textContent='Testing Gemini…';try{const j=await this.request('/test-gemini','POST');this.querySelector('p').textContent='Gemini responded · '+j.model+' · $'+Number(j.costUsd||0).toFixed(6);document.querySelector('maya-ai-meter')?.refresh(true);}catch(e){this.querySelector('p').textContent=e.message;}finally{b.disabled=false;}}
 async enable(){const b=this.querySelector('.enable-owner');b.disabled=true;try{await this.request('/enable','POST');await this.load();}catch(e){this.querySelector('p').textContent=e.message;}finally{b.disabled=false;}}
 async review(){const b=this.querySelector('.gmail-review');b.disabled=true;this.querySelector('p').textContent='Checking Gmail…';try{const j=await this.request('/gmail-review','POST'),host=this.querySelector('.gmail-candidates');host.replaceChildren();this.querySelector('p').textContent='Review correspondents before adding them.'+(j.pending?' More messages remain; review again to continue.':'');for(const c of j.candidates){const row=document.createElement('details'),title=document.createElement('summary'),note=document.createElement('p'),name=document.createElement('input'),add=document.createElement('button');title.textContent=c.email+' · '+c.subject;note.textContent=c.note;note.className='small';name.placeholder='Lead name';name.setAttribute('aria-label','Name for '+c.email);add.textContent='Add to Lead Station';add.onclick=async()=>{if(!name.value.trim()){name.focus();return;}add.disabled=true;try{const r=await this.request('/gmail-add','POST',{id:c.id,name:name.value});row.remove();this.querySelector('p').textContent='Added '+r.name+'. Refresh Lead Station to see it.';}catch(e){this.querySelector('p').textContent=e.message;add.disabled=false;}};row.append(title,note,name,add);host.append(row);}}catch(e){this.querySelector('p').textContent=e.message;}finally{b.disabled=false;}}
}
customElements.define('maya-owner-crm',OwnerCRM);
