/* Content + X/Y padding determines every shared capsule. Layout stays with pages. */
(() => {
  const glass = '.maya-pill:not([data-maya-pill="regular"]),.maya-glass-button,.maya-icon-button,button.glass-pill,.top-btn:not(.hamburger),button.action-btn,button.modal-text-btn,button.drawer-action,button.pin-cta,button.tos-agree,button.tos-decline,button.upload-choose-btn,button.tip-amt,button.primary,.pill,button.inv-btn,button.msg-call,button.msg-send,button.lead-tool,button.lead-cta,button.range-chip,button.metric-chip,button.wide,button.campaign,button.dissect-start,button.upload-btn,button.fab-src-pill,button.piece-pill,button.quality-pill,.dialog-actions button,.actions button,.toolbar button,.adm-tab,.maya-action-btn,.status-pill,maya-owner-crm button,#voice-bar,[data-maya-pill="glass"]';
  const regular = '.type-editor>summary,.finish-choice,[data-maya-pill="regular"]';
  const usage = {
    glass:[['Aesthetic Control','/aesthetics/aesthetic-control.html','Save, icons, status samples'],['Admin','/status.html','Messages actions, tabs, status pills, D/W/M, chart metrics'],['App','/','Listen and dialog actions'],['Playground','/playground.html','Listen and dialog actions'],['Outbound','/outbound.html','Actions and status pills'],['Brief','/backend.html','Dissect, pieces and Fabrics'],['Operation Room','/operations.html','Run and quality actions']],
    regular:[['Aesthetic Control','/aesthetics/aesthetic-control.html','All Edit menus and finish preset choices']]
  };
  function apply(value){
    const r=value.regularPill,g=value.glass;
    const palette={black:'0 0 0',gray:'13 17 32',blue:'35 76 125',yellow:'120 91 15',green:'23 91 59',pink:'115 46 70'};
    const border=name=>name==='black'?'0 0 0':name==='gray'?'170 181 196':'255 255 255';
    let css=`:root{--maya-pill-x:${value.pillX}px;--maya-pill-y:${value.pillY}px;--maya-regular-x:${r.paddingX}px;--maya-regular-y:${r.paddingY}px;--maya-icon-glyph:calc(var(--maya-control-icon-size,28px)*.6);}`;
    const both=`html body :is(${glass},${regular})`;
    css+=`${both}{align-items:center!important;justify-content:center!important;box-sizing:border-box!important;aspect-ratio:auto!important;flex:0 0 auto;inline-size:max-content!important;block-size:auto!important;min-inline-size:0!important;min-block-size:0!important;max-inline-size:100%;max-block-size:none!important;border-radius:100px!important;line-height:1.4!important;vertical-align:middle;gap:var(--maya-icon-pill-gap,6px)!important;white-space:normal;overflow-wrap:anywhere;text-align:center;}`;
    css+=`html body :is(${glass}){padding:var(--maya-pill-y) var(--maya-pill-x)!important;border:1px solid var(--maya-button-edge)!important;background-color:var(--maya-button-fill)!important;background-image:linear-gradient(125deg,rgb(255 255 255 / var(--maya-control-tint)),transparent 55%)!important;backdrop-filter:var(--maya-button-frost)!important;-webkit-backdrop-filter:var(--maya-button-frost)!important;box-shadow:inset 0 1px 1px rgb(255 255 255 / var(--maya-control-highlight)),inset 0 -1px 1px rgb(0 0 0 / .18),0 4px 16px rgb(0 0 0 / .22)!important;}`;
    // Preset previews and the current unsaved editor use the same formula with local values.
    css+=`html body :is(${glass})[data-finish]{background-color:rgb(3 15 29 / var(--finish-fill,${g.fill/100}))!important;border-color:rgb(var(--finish-border-rgb,${border(g.borderColor)}) / var(--finish-rim,${g.rim/100}))!important;backdrop-filter:blur(var(--finish-blur,${g.blur}px)) saturate(var(--finish-saturation,${g.saturation}%))!important;-webkit-backdrop-filter:blur(var(--finish-blur,${g.blur}px)) saturate(var(--finish-saturation,${g.saturation}%))!important;background-image:linear-gradient(125deg,rgb(255 255 255 / var(--finish-tint,${g.tint/100})),transparent 55%)!important;box-shadow:inset 0 1px 1px rgb(255 255 255 / var(--finish-highlight,${g.highlight/100})),inset 0 -1px 1px rgb(0 0 0 / .18),0 4px 16px rgb(0 0 0 / .22)!important;}`;
    css+=`html body :is(${regular}){display:inline-flex;padding:var(--maya-regular-y) var(--maya-regular-x)!important;border:1px solid rgb(${border(r.borderColor)} / ${r.rim/100})!important;background-color:rgb(${palette[r.background]||palette.black} / ${r.fill/100})!important;background-image:none!important;box-shadow:none!important;backdrop-filter:none!important;-webkit-backdrop-filter:none!important;font-family:var(--maya-type-P3-font)!important;font-size:var(--maya-type-P3-size)!important;font-weight:var(--maya-type-P3-weight)!important;font-style:var(--maya-type-P3-style)!important;text-transform:var(--maya-type-P3-case)!important;color:var(--maya-type-P3-color)!important;}`;
    css+=`${both}[hidden]{display:none!important}`;
    css+=`${both}:is(:hover,[data-preview-state="hover"]):not(:disabled){border-color:rgb(255 255 255 / .6)!important}${both}:is([aria-pressed="true"],[data-preview-state="selected"],[data-preview-state="pressed"],:active){border-color:var(--ui-accent,#adcdf8)!important}${both}:is(:focus-visible,[data-preview-state="focus"]){outline:2px solid var(--ui-accent,#adcdf8);outline-offset:3px}${both}:disabled{opacity:.5;cursor:not-allowed;box-shadow:none!important}`;
    // A glyph's own dimensions cannot depend on an unsized wrapper (the old Save bug).
    css+=`html body .maya-icon-button{aspect-ratio:auto!important;letter-spacing:normal!important}html body .maya-icon-button>span{display:grid!important;place-items:center;inline-size:var(--maya-icon-glyph);block-size:var(--maya-icon-glyph);font-size:var(--maya-icon-glyph);line-height:1!important}html body :is(.maya-icon-button svg,#save svg){display:block!important;inline-size:var(--maya-icon-glyph)!important;block-size:var(--maya-icon-glyph)!important;min-inline-size:var(--maya-icon-glyph);min-block-size:var(--maya-icon-glyph);fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;}`;
    // Native status selects remain the authenticated input over an intrinsic label.
    css+=`html body .lead-status{padding-right:calc(var(--maya-pill-x) + var(--maya-icon-pill-gap) + var(--maya-control-icon-size)*.45)!important}html body .lead-status::after{right:var(--maya-pill-x)!important}html body .status-pill::before{flex:none}html body .lead-status select{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;padding:0!important;}`;
    css+=`@media(forced-colors:active){${both}{background:ButtonFace!important;color:ButtonText!important;border-color:ButtonText!important;box-shadow:none!important;backdrop-filter:none!important}}`;
    let style=document.getElementById('maya-pill-control-style');if(!style){style=document.createElement('style');style.id='maya-pill-control-style';document.head.append(style);}style.textContent=css;
  }
  window.MayaPillControls={apply,usage,selectors:{glass,regular}};
})();
